import { Router } from 'express';
import { z } from 'zod';
import { query, getClient, releaseClient } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';
export const inventoryRouter = Router();
const id=z.number().int().positive();
const txSchema=z.object({warehouse_id:id,project_id:id.optional().nullable(),inventory_item_id:id,transaction_type:z.enum(['issue','transfer_in','transfer_out','adjustment']),quantity:z.number().refine(v=>v!==0),unit_cost:z.number().nonnegative().optional().nullable(),transaction_date:z.string().optional(),source_table:z.string().max(80).optional(),source_record_id:id.optional(),});
inventoryRouter.get('/warehouses',authorize('procurement','view'),asyncHandler(async(_req,res)=>res.json({success:true,data:await query('select * from warehouses order by code')})));
inventoryRouter.get('/items',authorize('procurement','view'),asyncHandler(async(_req,res)=>res.json({success:true,data:await query('select * from inventory_items order by item_code')})));
inventoryRouter.get('/stock',authorize('procurement','view'),asyncHandler(async(_req,res)=>res.json({success:true,data:await query(`select warehouse_id,inventory_item_id,sum(quantity) quantity_on_hand from inventory_transactions group by warehouse_id,inventory_item_id order by warehouse_id,inventory_item_id`)})));
inventoryRouter.post('/transactions',authorize('procurement','edit'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const b=txSchema.parse(req.body);if(['transfer_in','transfer_out'].includes(b.transaction_type))throw new AppError(422,'Use /inventory/transfer for warehouse transfers');if(b.transaction_type==='issue'&&b.quantity>=0)throw new AppError(422,'Issue quantity must be negative');const client=await getClient();try{await client.query('begin');const wh=(await client.query('select id from warehouses where id=$1 for update',[b.warehouse_id])).rows[0];if(!wh)throw new AppError(422,'Warehouse not found in current organization');if(b.transaction_type==='issue'){const stock=(await client.query(`select coalesce(sum(quantity),0)::numeric(18,3)::text as available, (coalesce(sum(quantity),0) >= abs($3::numeric)) as sufficient from inventory_transactions where warehouse_id=$1 and inventory_item_id=$2`,[b.warehouse_id,b.inventory_item_id,String(b.quantity)])).rows[0];if(!stock.sufficient)throw new AppError(409,`Insufficient stock. Available ${stock.available}`);}const rows=(await client.query(`insert into inventory_transactions(org_id,warehouse_id,project_id,inventory_item_id,transaction_type,quantity,unit_cost,transaction_date,source_table,source_record_id,created_by) values($1,$2,$3,$4,$5,$6,$7,coalesce($8::date,current_date),$9,$10,$11) returning *`,[req.user.org_id,b.warehouse_id,b.project_id??null,b.inventory_item_id,b.transaction_type,b.quantity,b.unit_cost??null,b.transaction_date??null,b.source_table??null,b.source_record_id??null,req.user.id])).rows;await client.query('commit');res.status(201).json({success:true,data:rows[0]});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));

inventoryRouter.post('/warehouses',authorize('procurement','manage'),asyncHandler(async(req,res)=>{const b=z.object({project_id:id.optional().nullable(),code:z.string().min(1).max(30),name:z.string().min(1).max(150)}).parse(req.body);const [r]=await query(`insert into warehouses(org_id,project_id,code,name) values($1,$2,$3,$4) returning *`,[req.user!.org_id,b.project_id??null,b.code,b.name]);res.status(201).json({success:true,data:r});}));
inventoryRouter.post('/items',authorize('procurement','manage'),asyncHandler(async(req,res)=>{const b=z.object({item_code:z.string().min(1).max(50),description:z.string().min(1),unit_of_measure:z.string().min(1).max(20),cost_code_id:id.optional().nullable()}).parse(req.body);const [r]=await query(`insert into inventory_items(org_id,item_code,description,unit_of_measure,cost_code_id) values($1,$2,$3,$4,$5) returning *`,[req.user!.org_id,b.item_code,b.description,b.unit_of_measure,b.cost_code_id??null]);res.status(201).json({success:true,data:r});}));

inventoryRouter.post('/transfer',authorize('procurement','edit'),asyncHandler(async(req,res)=>{
 if(!req.user)throw new AppError(401,'Authentication required');
 const b=z.object({from_warehouse_id:id,to_warehouse_id:id,project_id:id.optional().nullable(),inventory_item_id:id,quantity:z.number().positive(),unit_cost:z.number().nonnegative().optional().nullable(),transaction_date:z.string().optional()}).parse(req.body);
 if(b.from_warehouse_id===b.to_warehouse_id)throw new AppError(422,'Source and destination warehouses must differ');
 const client=await getClient();try{await client.query('begin');
  const wh=(await client.query('select id from warehouses where id=any($1::bigint[]) order by id for update',[[b.from_warehouse_id,b.to_warehouse_id]])).rows;if(wh.length!==2)throw new AppError(422,'Warehouse not found in current organization');
  const stock=(await client.query(`select coalesce(sum(quantity),0)::numeric(18,3)::text as available, (coalesce(sum(quantity),0) >= $3::numeric) as sufficient from inventory_transactions where warehouse_id=$1 and inventory_item_id=$2`,[b.from_warehouse_id,b.inventory_item_id,String(b.quantity)])).rows[0];if(!stock.sufficient)throw new AppError(409,`Insufficient stock. Available ${stock.available}`);
  const common=[req.user.org_id,b.project_id??null,b.inventory_item_id,b.quantity,b.unit_cost??null,b.transaction_date??null,req.user.id];
  const out=(await client.query(`insert into inventory_transactions(org_id,warehouse_id,project_id,inventory_item_id,transaction_type,quantity,unit_cost,transaction_date,source_table,created_by) values($1,$8,$2,$3,'transfer_out',-$4,$5,coalesce($6::date,current_date),'warehouse_transfer',$7) returning *`,[...common,b.from_warehouse_id])).rows[0];
  const inn=(await client.query(`insert into inventory_transactions(org_id,warehouse_id,project_id,inventory_item_id,transaction_type,quantity,unit_cost,transaction_date,source_table,source_record_id,created_by) values($1,$8,$2,$3,'transfer_in',$4,$5,coalesce($6::date,current_date),'warehouse_transfer',$9,$7) returning *`,[...common,b.to_warehouse_id,out.id])).rows[0];
  await client.query('commit');res.status(201).json({success:true,data:{transfer_out:out,transfer_in:inn}});
 }catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}
}));
