import { Router } from 'express'; import { z } from 'zod'; import { query } from '../../db/pool.js'; import { asyncHandler } from '../../middleware/asyncHandler.js'; import { authorize } from '../../middleware/authorize.js'; import { AppError } from '../../middleware/errors.js';
export const claimsRouter=Router(); const id=z.number().int().positive(); const schema=z.object({project_id:id,contract_id:id,event_id:id.optional().nullable(),notice_id:id.optional().nullable(),claim_no:z.string().min(1).max(40),claim_type:z.enum(['eot','cost','combined','other']),title:z.string().min(2).max(200),event_date:z.string().optional().nullable(),notice_date:z.string().optional().nullable(),claimed_days:z.number().int().nonnegative().default(0),claimed_amount:z.number().nonnegative().default(0),basis:z.string().optional().nullable()});
claimsRouter.get('/',authorize('contracts','view'),asyncHandler(async(q,r)=>r.json({success:true,data:await query('select * from contract_claims where org_id=$1 order by created_at desc',[q.user!.org_id])})));
// CC-030: claim view with its event, notice and time-bar position (shown, never auto-decided) and the contract's approved EOT total.
claimsRouter.get('/:id',authorize('contracts','view'),asyncHandler(async(req,res)=>{
 const claimId=Number(req.params.id); if(!Number.isInteger(claimId)||claimId<=0)throw new AppError(400,'Invalid claim id');
 const k=(await query<any>('select * from contract_claims where id=$1 and org_id=$2',[claimId,req.user!.org_id]))[0]; if(!k)throw new AppError(404,'Claim not found');
 const event=k.event_id?(await query<any>('select * from contract_events where id=$1',[k.event_id]))[0]??null:null;
 const n=k.notice_id?(await query<any>(`select n.id,n.status,n.deadline,n.issued_at,n.issued_late,r.clause_ref,r.is_condition_precedent from contract_notices n join contract_obligation_rules r on r.id=n.rule_id where n.id=$1`,[k.notice_id]))[0]??null:null;
 const eot=(await query<any>(`select coalesce(sum(approved_days),0)::int as days from contract_claims where contract_id=$1 and status in ('approved','partially_approved')`,[k.contract_id]))[0];
 res.json({success:true,data:{...k,event,notice:n,time_bar:n?{notice_status:n.status,deadline:n.deadline,notice_issued_late:n.issued_late===true,condition_precedent:n.is_condition_precedent===true,clause_ref:n.clause_ref}:{notice_status:'no_linked_notice'},contract_approved_eot_days:eot.days}});
}));
claimsRouter.post('/',authorize('contracts','create'),asyncHandler(async(q,r)=>{if(!q.user)throw new AppError(401,'Authentication required');const b=schema.parse(q.body);const x=await query(`insert into contract_claims(org_id,project_id,contract_id,claim_no,claim_type,title,event_date,notice_date,claimed_days,claimed_amount,basis,created_by,event_id,notice_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`,[q.user.org_id,b.project_id,b.contract_id,b.claim_no,b.claim_type,b.title,b.event_date??null,b.notice_date??null,b.claimed_days,b.claimed_amount,b.basis??null,q.user.id,b.event_id??null,b.notice_id??null]);r.status(201).json({success:true,data:x[0]})}));

claimsRouter.patch('/:id',authorize('contracts','edit'),asyncHandler(async(req,res)=>{
 const claimId=Number(req.params.id); if(!Number.isInteger(claimId)||claimId<=0)throw new AppError(400,'Invalid claim id');
 const b=z.object({title:z.string().min(2).max(200).optional(),event_date:z.string().nullable().optional(),notice_date:z.string().nullable().optional(),claimed_days:z.number().int().nonnegative().optional(),claimed_amount:z.number().nonnegative().optional(),approved_days:z.number().int().nonnegative().nullable().optional(),approved_amount:z.number().nonnegative().nullable().optional(),determination_reason:z.string().trim().max(4000).optional(),basis:z.string().nullable().optional()}).parse(req.body);
 const current=(await query<any>('select * from contract_claims where id=$1 and org_id=$2',[claimId,req.user!.org_id]))[0]; if(!current)throw new AppError(404,'Claim not found'); if((b.approved_days!==undefined||b.approved_amount!==undefined)&&Number(current.created_by)===req.user!.id)throw new AppError(403,'Segregation of duties: the claim author cannot determine the claim'); const determinationOnly=['under_review'].includes(current.status); if(!['draft','notified','under_review'].includes(current.status))throw new AppError(409,'Claim is immutable in its current status'); if(determinationOnly && (b.title!==undefined||b.event_date!==undefined||b.notice_date!==undefined||b.claimed_days!==undefined||b.claimed_amount!==undefined||b.basis!==undefined))throw new AppError(409,'Only determination fields may be edited while claim is under review'); if(!determinationOnly && (b.approved_days!==undefined||b.approved_amount!==undefined))throw new AppError(409,'Determination fields may only be set while claim is under review'); const [row]=await query(`update contract_claims set title=coalesce($2,title),event_date=coalesce($3::date,event_date),notice_date=coalesce($4::date,notice_date),claimed_days=coalesce($5,claimed_days),claimed_amount=coalesce($6,claimed_amount),approved_days=coalesce($7::int,approved_days),approved_amount=coalesce($8::numeric,approved_amount),basis=coalesce($9,basis),determination_reason=coalesce($11,determination_reason),determined_by=case when $7::int is not null or $8::numeric is not null then $10::bigint else determined_by end,determined_at=case when $7::int is not null or $8::numeric is not null then now() else determined_at end,updated_at=now() where id=$1 returning *`,[claimId,b.title??null,b.event_date??null,b.notice_date??null,b.claimed_days??null,b.claimed_amount??null,b.approved_days??null,b.approved_amount??null,b.basis??null,req.user!.id,b.determination_reason??null]);
 if(!row)throw new AppError(404,'Claim not found');res.json({success:true,data:row});
}));
claimsRouter.post('/:id/status',authorize('contracts','approve'),asyncHandler(async(req,res)=>{
 const claimId=Number(req.params.id); if(!Number.isInteger(claimId)||claimId<=0)throw new AppError(400,'Invalid claim id');
 const b=z.object({status:z.enum(['notified','submitted','under_review','approved','partially_approved','rejected','withdrawn']),reason:z.string().trim().max(4000).optional()})
  .refine(v=>!['approved','partially_approved','rejected','withdrawn'].includes(v.status)||(v.reason??'').length>=5,{message:'A final decision or withdrawal needs a reason (at least 5 characters)',path:['reason']}).parse(req.body);
 const current=(await query<any>('select * from contract_claims where id=$1 and org_id=$2',[claimId,req.user!.org_id]))[0]; if(!current)throw new AppError(404,'Claim not found'); if(['approved','partially_approved','rejected'].includes(b.status) && Number(current.created_by)===req.user!.id)throw new AppError(403,'Segregation of duties: claim creator cannot make the final determination');
 const allowed:Record<string,string[]>={draft:['notified','withdrawn'],notified:['submitted','withdrawn'],submitted:['under_review','withdrawn'],under_review:['approved','partially_approved','rejected'],partially_approved:[],approved:[],rejected:[],withdrawn:[]};
 if(!(allowed[current.status]||[]).includes(b.status))throw new AppError(409,`Invalid claim transition ${current.status} -> ${b.status}`);
 if(['approved','partially_approved'].includes(b.status) && current.claim_type!=='cost' && current.approved_days==null)throw new AppError(422,'approved_days is required before approving an EOT/combined claim');
 if(['approved','partially_approved'].includes(b.status) && current.claim_type!=='eot' && current.approved_amount==null)throw new AppError(422,'approved_amount is required before approving a cost/combined claim');
 const [row]=await query(`update contract_claims set status=$2::varchar,decision_reason=coalesce($4::text,decision_reason),final_decided_by=case when $2::varchar in ('approved','partially_approved','rejected') then $3::bigint else final_decided_by end,final_decided_at=case when $2::varchar in ('approved','partially_approved','rejected') then now() else final_decided_at end,updated_at=now() where id=$1 returning *`,[claimId,b.status,req.user!.id,b.reason??null]);res.json({success:true,data:row});
}));
