import { Router } from 'express';
import { z } from 'zod';
import { query, getClient, releaseClient } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';
import { createApprovalInstance } from '../../services/approval.service.js';

export const subcontractsRouter = Router();
const id = z.number().int().positive();
const subcontractSchema = z.object({ project_id:id, vendor_id:id, package_name:z.string().min(1).max(200), scope_of_work:z.string().optional(), contract_value:z.number().positive(), currency_id:id, cost_code_id:id.optional().nullable(), retention_percent:z.number().min(0).max(100).optional().nullable(), advance_payment_percent:z.number().min(0).max(100).optional().nullable(), start_date:z.string().optional().nullable(), completion_date:z.string().optional().nullable() });
const certificateSchema = z.object({ subcontract_id:id, project_id:id, certificate_no:z.string().min(1).max(30), period_from:z.string(), period_to:z.string(), gross_work_done:z.number().nonnegative().default(0), less_retention:z.number().nonnegative().default(0), less_advance_recovery:z.number().nonnegative().default(0), less_previous_paid:z.number().nonnegative().default(0), penalties_deductions:z.number().nonnegative().default(0) });
const lineSchema = z.object({ description:z.string().min(1), quantity_this_period:z.number().nonnegative(), cumulative_quantity:z.number().nonnegative(), unit_rate:z.number().nonnegative() });
const parseId=(raw:string)=>{const n=Number(raw);if(!Number.isInteger(n)||n<=0)throw new AppError(400,'Invalid id');return n;};

subcontractsRouter.get('/',authorize('contracts','view'),asyncHandler(async(_req,res)=>{const rows=await query(`select s.*,p.project_code,v.vendor_name,c.code currency_code from subcontracts s join projects p on p.id=s.project_id join vendors_subcontractors v on v.id=s.vendor_id join currencies c on c.id=s.currency_id order by s.created_at desc limit 500`);res.json({success:true,data:rows});}));
subcontractsRouter.post('/',authorize('contracts','create'),asyncHandler(async(req,res)=>{const b=subcontractSchema.parse(req.body);const client=await getClient();try{await client.query('begin');const project=(await client.query('select id,org_id,currency_id from projects where id=$1 for share',[b.project_id])).rows[0];if(!project)throw new AppError(404,'Project not found');if(Number(project.org_id)!==req.user!.org_id)throw new AppError(403,'Project belongs to another organization');const vendor=(await client.query('select id from vendors_subcontractors where id=$1 and org_id=$2 and is_active=true',[b.vendor_id,req.user!.org_id])).rows[0];if(!vendor)throw new AppError(422,'Subcontractor not found in current organization');const row=(await client.query(`insert into subcontracts(org_id,project_id,vendor_id,package_name,scope_of_work,contract_value,currency_id,cost_code_id,retention_percent,advance_payment_percent,start_date,completion_date,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'draft',$13) returning *`,[req.user!.org_id,b.project_id,b.vendor_id,b.package_name,b.scope_of_work??null,b.contract_value,b.currency_id,b.cost_code_id??null,b.retention_percent??null,b.advance_payment_percent??null,b.start_date??null,b.completion_date??null,req.user!.id])).rows[0];await client.query('commit');res.status(201).json({success:true,data:row});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
subcontractsRouter.post('/:id/submit-approval',authorize('contracts','approve'),asyncHandler(async(req,res)=>{const subcontractId=parseId(req.params.id);const client=await getClient();try{await client.query('begin');const s=(await client.query('select * from subcontracts where id=$1 for update',[subcontractId])).rows[0];if(!s)throw new AppError(404,'Subcontract not found');if(Number(s.org_id)!==req.user!.org_id)throw new AppError(403,'Subcontract belongs to another organization');if(s.status!=='draft')throw new AppError(409,'Only draft subcontracts can be submitted for approval');const approval=await createApprovalInstance(client,{org_id:req.user!.org_id,module:'subcontract_signing',record_id:subcontractId,amount:String(s.contract_value),currency_id:s.currency_id,initiated_by:req.user!.id});await client.query('update subcontracts set approval_instance_id=$2,updated_at=now() where id=$1',[subcontractId,approval.id]);await client.query('commit');res.json({success:true,data:{approval}});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
subcontractsRouter.get('/certificates',authorize('contracts','view'),asyncHandler(async(_req,res)=>{const rows=await query(`select sc.*,s.package_name,v.vendor_name from subcontract_certificates sc join subcontracts s on s.id=sc.subcontract_id join vendors_subcontractors v on v.id=s.vendor_id order by sc.created_at desc limit 500`);res.json({success:true,data:rows});}));
subcontractsRouter.post('/certificates',authorize('contracts','create'),asyncHandler(async(req,res)=>{const b=certificateSchema.parse(req.body);const client=await getClient();try{await client.query('begin');const s=(await client.query('select * from subcontracts where id=$1',[b.subcontract_id])).rows[0];if(!s)throw new AppError(404,'Subcontract not found');if(Number(s.org_id)!==req.user!.org_id||Number(s.project_id)!==b.project_id)throw new AppError(403,'Subcontract/project organization mismatch');const row=(await client.query(`insert into subcontract_certificates(org_id,subcontract_id,project_id,certificate_no,period_from,period_to,gross_work_done,less_retention,less_advance_recovery,less_previous_paid,penalties_deductions,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'draft',$12) returning *`,[req.user!.org_id,b.subcontract_id,b.project_id,b.certificate_no,b.period_from,b.period_to,b.gross_work_done,b.less_retention,b.less_advance_recovery,b.less_previous_paid,b.penalties_deductions,req.user!.id])).rows[0];await client.query('commit');res.status(201).json({success:true,data:row});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
subcontractsRouter.post('/certificates/:id/lines',authorize('contracts','create'),asyncHandler(async(req,res)=>{const b=lineSchema.parse(req.body);const certificateId=parseId(req.params.id);const cert=(await query('select org_id from subcontract_certificates where id=$1',[certificateId]))[0];if(!cert)throw new AppError(404,'Certificate not found');if(Number(cert.org_id)!==req.user!.org_id)throw new AppError(403,'Certificate belongs to another organization');const rows=await query(`insert into subcontract_certificate_lines(org_id,certificate_id,description,quantity_this_period,cumulative_quantity,unit_rate) values($1,$2,$3,$4,$5,$6) returning *`,[req.user!.org_id,certificateId,b.description,b.quantity_this_period,b.cumulative_quantity,b.unit_rate]);res.status(201).json({success:true,data:rows[0]});}));
subcontractsRouter.post('/certificates/:id/verify',authorize('site','approve'),asyncHandler(async(req,res)=>{const certificateId=parseId(req.params.id);const rows=await query(`update subcontract_certificates set status='site_verified',site_verified_by=$3,site_verified_at=now(),updated_at=now() where id=$1 and org_id=$2 and status='draft' and created_by is not null and created_by<>$3 returning *`,[certificateId,req.user!.org_id,req.user!.id]);if(!rows[0])throw new AppError(409,'Certificate is not in draft state, maker identity is missing, maker attempted self-verification, or certificate is outside your organization');res.json({success:true,data:rows[0]});}));
subcontractsRouter.post('/certificates/:id/qs-certify',authorize('contracts','approve'),asyncHandler(async(req,res)=>{const certificateId=parseId(req.params.id);const rows=await query(`update subcontract_certificates set status='qs_certified',certified_by=$3,qs_certified_by=$3,qs_certified_at=now(),updated_at=now() where id=$1 and org_id=$2 and status='site_verified' and created_by is not null and created_by<>$3 and site_verified_by is not null and site_verified_by<>$3 returning *`,[certificateId,req.user!.org_id,req.user!.id]);if(!rows[0])throw new AppError(409,'Certificate is not site-verified, maker/site verifier segregation failed, or certificate is outside your organization');res.json({success:true,data:rows[0]});}));
subcontractsRouter.post('/certificates/:id/submit-approval',authorize('contracts','approve'),asyncHandler(async(req,res)=>{const certificateId=parseId(req.params.id);const client=await getClient();try{await client.query('begin');const cert=(await client.query('select * from subcontract_certificates where id=$1 for update',[certificateId])).rows[0];if(!cert)throw new AppError(404,'Certificate not found');if(Number(cert.org_id)!==req.user!.org_id)throw new AppError(403,'Certificate belongs to another organization');if(cert.status!=='qs_certified')throw new AppError(409,'Certificate must be QS-certified before approval');const approval=await createApprovalInstance(client,{org_id:req.user!.org_id,module:'subcontract_certificate',record_id:certificateId,amount:String(cert.net_amount_due),currency_id:(await client.query('select currency_id from subcontracts where id=$1',[cert.subcontract_id])).rows[0]?.currency_id??null,initiated_by:req.user!.id});await client.query('update subcontract_certificates set approval_instance_id=$2,updated_at=now() where id=$1',[certificateId,approval.id]);await client.query('commit');res.json({success:true,data:{approval}});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
