import { Router } from 'express';
import { z } from 'zod';
import { query, getClient, releaseClient } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';
import { createApprovalInstance } from '../../services/approval.service.js';

export const tenderingRouter = Router();
const id=z.number().int().positive();
const tenderSchema=z.object({ tender_ref:z.string().min(2).max(50), tender_title:z.string().min(2).max(200), tender_type:z.enum(['public','private','invited']).default('private'), client_id:id.optional().nullable(), opportunity_id:id.optional().nullable(), submission_deadline:z.string().optional().nullable(), bond_required:z.boolean().default(false), bond_amount:z.number().nonnegative().optional().nullable(), estimated_value:z.number().nonnegative().optional().nullable(), currency_id:id.optional().nullable(), assigned_estimator_id:id.optional().nullable() });
const clarificationSchema=z.object({question:z.string().min(3),answer:z.string().optional().nullable(),status:z.enum(['open','answered']).optional()});
const docSchema=z.object({doc_type:z.enum(['rfp','drawings','specs','boq_template','addendum','other']),document_id:id});

function parseId(raw:string){const n=Number(raw);if(!Number.isInteger(n)||n<=0)throw new AppError(400,'Invalid id');return n;}

tenderingRouter.get('/tenders',authorize('tendering','view'),asyncHandler(async(_req,res)=>{const rows=await query(`select t.*,c.client_name,u.full_name assigned_estimator_name from tenders t left join clients c on c.id=t.client_id left join users u on u.id=t.assigned_estimator_id order by t.created_at desc limit 500`);res.json({success:true,data:rows});}));
tenderingRouter.get('/tenders/:id',authorize('tendering','view'),asyncHandler(async(req,res)=>{const tenderId=parseId(req.params.id);const tender=(await query(`select t.*,c.client_name,u.full_name assigned_estimator_name from tenders t left join clients c on c.id=t.client_id left join users u on u.id=t.assigned_estimator_id where t.id=$1`,[tenderId]))[0];if(!tender)throw new AppError(404,'Tender not found');const clarifications=await query(`select tc.*,u.full_name raised_by_name from tender_clarifications tc join users u on u.id=tc.raised_by where tc.tender_id=$1 order by tc.raised_date desc`,[tenderId]);const documents=await query(`select td.*,d.doc_number,d.file_name from tender_documents td left join documents d on d.id=td.document_id where td.tender_id=$1 order by td.created_at desc`,[tenderId]);const boq=await query(`select * from boq_master where tender_id=$1 order by item_no`,[tenderId]);res.json({success:true,data:{tender,clarifications,documents,boq}});}));
tenderingRouter.post('/tenders',authorize('tendering','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const b=tenderSchema.parse(req.body);const rows=await query(`insert into tenders(org_id,opportunity_id,client_id,tender_ref,tender_title,tender_type,submission_deadline,bond_required,bond_amount,estimated_value,currency_id,assigned_estimator_id,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'invited',$13) returning *`,[req.user.org_id,b.opportunity_id??null,b.client_id??null,b.tender_ref,b.tender_title,b.tender_type,b.submission_deadline??null,b.bond_required,b.bond_amount??null,b.estimated_value??null,b.currency_id??null,b.assigned_estimator_id??null,req.user.id]);res.status(201).json({success:true,data:rows[0]});}));
tenderingRouter.patch('/tenders/:id',authorize('tendering','edit'),asyncHandler(async(req,res)=>{
 const tenderId=parseId(req.params.id);
 const b=tenderSchema.partial().extend({status:z.enum(['invited','in_progress','won','lost','withdrawn']).optional(),awarded_value:z.number().nonnegative().optional().nullable(),loss_reason:z.string().optional().nullable()}).parse(req.body);
 const current=(await query<any>(`select t.*,ai.status approval_status from tenders t left join approval_instances ai on ai.id=t.approval_instance_id where t.id=$1`,[tenderId]))[0];
 if(!current)throw new AppError(404,'Tender not found');
 if(current.approval_status==='pending')throw new AppError(409,'Tender has a pending submission approval and cannot be edited');
 const transitions:Record<string,string[]>={invited:['in_progress','withdrawn'],in_progress:['withdrawn'],submitted:['won','lost','withdrawn'],won:[],lost:[],withdrawn:[]};
 if(b.status && b.status!==current.status && !(transitions[current.status]||[]).includes(b.status))throw new AppError(409,`Invalid tender transition ${current.status} -> ${b.status}`);
 if(['won','lost','withdrawn'].includes(current.status))throw new AppError(409,'Finalized tender is immutable');
 if(b.status==='won' && (b.awarded_value===undefined || b.awarded_value===null))throw new AppError(422,'awarded_value is required when marking a tender won');
 if(b.status==='lost' && !b.loss_reason?.trim())throw new AppError(422,'loss_reason is required when marking a tender lost');
 const rows=await query(`update tenders set tender_ref=coalesce($2,tender_ref),tender_title=coalesce($3,tender_title),tender_type=coalesce($4,tender_type),client_id=coalesce($5,client_id),opportunity_id=coalesce($6,opportunity_id),submission_deadline=coalesce($7,submission_deadline),bond_required=coalesce($8,bond_required),bond_amount=coalesce($9,bond_amount),estimated_value=coalesce($10,estimated_value),currency_id=coalesce($11,currency_id),assigned_estimator_id=coalesce($12,assigned_estimator_id),status=coalesce($13,status),awarded_value=coalesce($14,awarded_value),loss_reason=coalesce($15,loss_reason),updated_at=now() where id=$1 returning *`,[tenderId,b.tender_ref??null,b.tender_title??null,b.tender_type??null,b.client_id??null,b.opportunity_id??null,b.submission_deadline??null,b.bond_required??null,b.bond_amount??null,b.estimated_value??null,b.currency_id??null,b.assigned_estimator_id??null,b.status??null,b.awarded_value??null,b.loss_reason??null]);
 res.json({success:true,data:rows[0]});
}));
tenderingRouter.post('/tenders/:id/submit-approval',authorize('tendering','approve'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const tenderId=parseId(req.params.id);const client=await getClient();try{await client.query('begin');const tender=(await client.query(`select * from tenders where id=$1 for update`,[tenderId])).rows[0];if(!tender)throw new AppError(404,'Tender not found');if(!['in_progress'].includes(tender.status))throw new AppError(409,'Only in-progress tenders can be submitted');const approval=await createApprovalInstance(client,{org_id:req.user.org_id,module:'tender_submission',record_id:tenderId,amount:tender.estimated_value===null?null:String(tender.estimated_value),currency_id:tender.currency_id,initiated_by:req.user.id});await client.query(`update tenders set approval_instance_id=$2,updated_at=now() where id=$1`,[tenderId,approval.id]);await client.query('commit');res.json({success:true,data:{approval}});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
tenderingRouter.post('/tenders/:id/clarifications',authorize('tendering','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const tenderId=parseId(req.params.id);const b=clarificationSchema.parse(req.body);const rows=await query(`insert into tender_clarifications(org_id,tender_id,question,answer,raised_by,answered_date,status) values($1,$2,$3,$4,$5,case when $4 is not null then now() else null end,coalesce($6,'open')) returning *`,[req.user.org_id,tenderId,b.question,b.answer??null,req.user.id,b.status??null]);res.status(201).json({success:true,data:rows[0]});}));
tenderingRouter.patch('/clarifications/:id',authorize('tendering','edit'),asyncHandler(async(req,res)=>{const clarificationId=parseId(req.params.id);const b=clarificationSchema.partial().parse(req.body);const rows=await query(`update tender_clarifications set question=coalesce($2,question),answer=$3,status=coalesce($4,status),answered_date=case when coalesce($4,status)='answered' then coalesce(answered_date,now()) else answered_date end where id=$1 returning *`,[clarificationId,b.question??null,b.answer??null,b.status??null]);if(!rows[0])throw new AppError(404,'Clarification not found');res.json({success:true,data:rows[0]});}));
tenderingRouter.post('/tenders/:id/documents',authorize('tendering','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const tenderId=parseId(req.params.id);const b=docSchema.parse(req.body);const rows=await query(`insert into tender_documents(org_id,tender_id,doc_type,document_id) values($1,$2,$3,$4) returning *`,[req.user.org_id,tenderId,b.doc_type,b.document_id]);res.status(201).json({success:true,data:rows[0]});}));
