import { Router } from 'express';
import { healthRouter } from '../modules/health/health.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { usersRouter } from '../modules/users/users.routes.js';
import { rolesRouter } from '../modules/roles/roles.routes.js';
import { projectsRouter } from '../modules/projects/projects.routes.js';
import { costCodesRouter } from '../modules/costCodes/costCodes.routes.js';
import { boqRouter } from '../modules/boq/boq.routes.js';
import { costTransactionsRouter } from '../modules/costTransactions/costTransactions.routes.js';
import { approvalsRouter } from '../modules/approvals/approvals.routes.js';
import { procurementRouter } from '../modules/procurement/procurement.routes.js';
import { financeRouter } from '../modules/finance/finance.routes.js';
import { technicalOfficeRouter } from '../modules/technicalOffice/technicalOffice.routes.js';
import { planningRouter } from '../modules/planning/planning.routes.js';
import { siteRouter } from '../modules/site/site.routes.js';
import { hrRouter } from '../modules/hr/hr.routes.js';
import { assetsRouter } from '../modules/assets/assets.routes.js';
import { qaqcRouter } from '../modules/qaqc/qaqc.routes.js';
import { hseRouter } from '../modules/hse/hse.routes.js';
import { edmsRouter } from '../modules/edms/edms.routes.js';
import { dashboardsRouter } from '../modules/dashboards/dashboards.routes.js';
import { reportsRouter } from '../modules/reports/reports.routes.js';
import { portalsRouter } from '../modules/portals/portals.routes.js';
import { notificationsRouter } from '../modules/notifications/notifications.routes.js';
import { runtimeValidationRouter } from '../modules/runtimeValidation/runtimeValidation.routes.js';
import { clientsRouter } from '../modules/clients/clients.routes.js';
import { crmRouter } from '../modules/crm/crm.routes.js';
import { tenderingRouter } from '../modules/tendering/tendering.routes.js';
import { contractsRouter } from '../modules/contracts/contracts.routes.js';
import { subcontractsRouter } from '../modules/subcontracts/subcontracts.routes.js';
import { inventoryRouter } from '../modules/inventory/inventory.routes.js';
import { claimsRouter } from '../modules/claims/claims.routes.js';
import { referenceDataRouter } from '../modules/referenceData/referenceData.routes.js';
import { authenticate } from '../middleware/authenticate.js';
import { contractAdminRouter } from '../modules/contractAdmin/contractAdmin.routes.js';
import { onboardingRouter } from '../modules/onboarding/onboarding.routes.js';
import { vendorsRouter } from '../modules/vendors/vendors.routes.js';
import { aiPlatformRouter } from '../modules/aiPlatform/aiPlatform.routes.js';
import { commercialPlatformRouter } from '../modules/commercialPlatform/commercialPlatform.routes.js';
import { automationRouter } from '../modules/automation/automation.routes.js';
import { knowledgeRouter } from '../modules/knowledge/knowledge.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);

apiRouter.use(authenticate);
apiRouter.use('/reference-data', referenceDataRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/clients', clientsRouter);
apiRouter.use('/crm', crmRouter);
apiRouter.use('/tendering', tenderingRouter);
apiRouter.use('/contracts', contractsRouter);
apiRouter.use('/subcontracts', subcontractsRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/claims', claimsRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/projects', projectsRouter);
apiRouter.use('/cost-codes', costCodesRouter);
apiRouter.use('/boq', boqRouter);
apiRouter.use('/cost-transactions', costTransactionsRouter);
apiRouter.use('/approvals', approvalsRouter);
apiRouter.use('/procurement', procurementRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/technical-office', technicalOfficeRouter);
apiRouter.use('/planning', planningRouter);
apiRouter.use('/site', siteRouter);
apiRouter.use('/hr', hrRouter);
apiRouter.use('/assets', assetsRouter);
apiRouter.use('/qaqc', qaqcRouter);
apiRouter.use('/hse', hseRouter);
apiRouter.use('/edms', edmsRouter);
apiRouter.use('/dashboards', dashboardsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/portals', portalsRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/runtime-validation', runtimeValidationRouter);
apiRouter.use('/ai-platform', aiPlatformRouter);
apiRouter.use('/vendors', vendorsRouter);
apiRouter.use('/onboarding', onboardingRouter);
apiRouter.use('/contract-admin', contractAdminRouter);
apiRouter.use('/commercial-platform', commercialPlatformRouter);
apiRouter.use('/automation', automationRouter);
apiRouter.use('/knowledge', knowledgeRouter);
