import { Router } from 'express';
import { z } from 'zod';
import { query, getClient, releaseClient } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';
import { createApprovalInstance } from '../../services/approval.service.js';

export const contractsRouter = Router();
const id=z.number().int().positive();
const contractSchema=z.object({ project_id:id,client_id:id,contract_type:z.enum(['lump_sum','unit_price','cost_plus']),contract_form:z.enum(['fidic_red','fidic_yellow','fidic_silver','custom']).optional().nullable(),contract_value:z.number().nonnegative(),currency_id:id,signing_date:z.string().optional().nullable(),effective_date:z.string().optional().nullable(),completion_period_days:z.number().int().nonnegative().optional().nullable(),defects_liability_months:z.number().int().nonnegative().optional().nullable(),retention_percent:z.number().min(0).max(100).optional().nullable(),advance_payment_percent:z.number().min(0).max(100).optional().nullable(),performance_bond_percent:z.number().min(0).max(100).optional().nullable(),liquidated_damages_rate:z.number().nonnegative().optional().nullable()});
const clauseSchema=z.object({clause_ref:z.string().max(30).optional().nullable(),clause_title:z.string().max(200).optional().nullable(),clause_text:z.string().optional().nullable(),category:z.enum(['payment','variation','dispute','termination','general']).optional().nullable()});
const variationSchema=z.object({project_id:id,contract_id:id,variation_no:z.string().min(1).max(20),description:z.string().min(2),reason:z.enum(['client_request','design_change','site_condition','other']).optional().nullable(),cost_impact:z.number().default(0),time_impact_days:z.number().int().default(0)});
const lineSchema=z.object({project_boq_item_id:id.optional().nullable(),description:z.string().min(2),unit_of_measure:z.string().min(1).max(20),quantity:z.number(),unit_rate:z.number().nonnegative(),action:z.enum(['add','omit','amend'])});
function parseId(raw:string){const n=Number(raw);if(!Number.isInteger(n)||n<=0)throw new AppError(400,'Invalid id');return n;}

contractsRouter.get('/',authorize('contracts','view'),asyncHandler(async(_req,res)=>{const rows=await query(`select c.*,p.project_code,p.project_name,cl.client_name,cur.code currency_code from contracts c join projects p on p.id=c.project_id join clients cl on cl.id=c.client_id join currencies cur on cur.id=c.currency_id order by c.created_at desc limit 500`);res.json({success:true,data:rows});}));
contractsRouter.get('/:id',authorize('contracts','view'),asyncHandler(async(req,res)=>{const contractId=parseId(req.params.id);const contract=(await query(`select c.*,p.project_code,p.project_name,cl.client_name,cur.code currency_code from contracts c join projects p on p.id=c.project_id join clients cl on cl.id=c.client_id join currencies cur on cur.id=c.currency_id where c.id=$1`,[contractId]))[0];if(!contract)throw new AppError(404,'Contract not found');const clauses=await query(`select * from contract_clauses where contract_id=$1 order by id`,[contractId]);const variations=await query(`select * from variations where contract_id=$1 order by created_at desc`,[contractId]);res.json({success:true,data:{contract,clauses,variations}});}));
contractsRouter.post('/',authorize('contracts','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const b=contractSchema.parse(req.body);const client=await getClient();try{await client.query('begin');const project=(await client.query(`select * from projects where id=$1 for share`,[b.project_id])).rows[0];if(!project)throw new AppError(404,'Project not found');if(Number(project.org_id)!==req.user.org_id)throw new AppError(403,'Project belongs to another organization');const cl=(await client.query(`select id from clients where id=$1 and org_id=$2 and is_active=true`,[b.client_id,req.user.org_id])).rows[0];if(!cl)throw new AppError(422,'Client not found in current organization');const rows=await client.query(`insert into contracts(org_id,project_id,client_id,contract_type,contract_form,contract_value,currency_id,signing_date,effective_date,completion_period_days,defects_liability_months,retention_percent,advance_payment_percent,performance_bond_percent,liquidated_damages_rate,contract_status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'draft',$16) returning *`,[req.user.org_id,b.project_id,b.client_id,b.contract_type,b.contract_form??null,b.contract_value,b.currency_id,b.signing_date??null,b.effective_date??null,b.completion_period_days??null,b.defects_liability_months??null,b.retention_percent??null,b.advance_payment_percent??null,b.performance_bond_percent??null,b.liquidated_damages_rate??null,req.user.id]);await client.query('commit');res.status(201).json({success:true,data:rows.rows[0]});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
contractsRouter.patch('/:id',authorize('contracts','edit'),asyncHandler(async(req,res)=>{
 const contractId=parseId(req.params.id);
 const b=contractSchema.partial().extend({contract_status:z.enum(['draft','active','closed','terminated']).optional()}).parse(req.body);
 const current=(await query<any>(`select c.*,ai.status approval_status from contracts c left join approval_instances ai on ai.id=c.approval_instance_id where c.id=$1`,[contractId]))[0];
 if(!current)throw new AppError(404,'Contract not found');
 if(current.approval_status==='pending'||current.contract_status==='under_review')throw new AppError(409,'Contract is under approval and cannot be edited');
 if(current.contract_status==='signed' && b.contract_status && !['active','terminated'].includes(b.contract_status))throw new AppError(409,'Signed contract may only transition to active or terminated');
 if(current.contract_status==='active' && b.contract_status && !['closed','terminated'].includes(b.contract_status))throw new AppError(409,'Active contract may only transition to closed or terminated');
 if(['closed','terminated'].includes(current.contract_status))throw new AppError(409,'Closed/terminated contract is immutable');
 const rows=await query(`update contracts set project_id=coalesce($2,project_id),client_id=coalesce($3,client_id),contract_type=coalesce($4,contract_type),contract_form=coalesce($5,contract_form),contract_value=coalesce($6,contract_value),currency_id=coalesce($7,currency_id),signing_date=coalesce($8,signing_date),effective_date=coalesce($9,effective_date),completion_period_days=coalesce($10,completion_period_days),defects_liability_months=coalesce($11,defects_liability_months),retention_percent=coalesce($12,retention_percent),advance_payment_percent=coalesce($13,advance_payment_percent),performance_bond_percent=coalesce($14,performance_bond_percent),liquidated_damages_rate=coalesce($15,liquidated_damages_rate),contract_status=coalesce($16,contract_status),updated_at=now() where id=$1 returning *`,[contractId,b.project_id??null,b.client_id??null,b.contract_type??null,b.contract_form??null,b.contract_value??null,b.currency_id??null,b.signing_date??null,b.effective_date??null,b.completion_period_days??null,b.defects_liability_months??null,b.retention_percent??null,b.advance_payment_percent??null,b.performance_bond_percent??null,b.liquidated_damages_rate??null,b.contract_status??null]);
 res.json({success:true,data:rows[0]});
}));
contractsRouter.post('/:id/submit-approval',authorize('contracts','approve'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const contractId=parseId(req.params.id);const client=await getClient();try{await client.query('begin');const contract=(await client.query(`select * from contracts where id=$1 for update`,[contractId])).rows[0];if(!contract)throw new AppError(404,'Contract not found');if(contract.contract_status!=='draft')throw new AppError(409,'Only draft contracts can be submitted for approval');const approval=await createApprovalInstance(client,{org_id:req.user.org_id,module:'contract_signing',record_id:contractId,amount:String(contract.contract_value),currency_id:contract.currency_id,initiated_by:req.user.id});await client.query(`update contracts set contract_status='under_review',approval_instance_id=$2,updated_at=now() where id=$1`,[contractId,approval.id]);await client.query('commit');res.json({success:true,data:{approval}});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));
contractsRouter.post('/:id/clauses',authorize('contracts','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const contractId=parseId(req.params.id);const b=clauseSchema.parse(req.body);const rows=await query(`insert into contract_clauses(org_id,contract_id,clause_ref,clause_title,clause_text,category) values($1,$2,$3,$4,$5,$6) returning *`,[req.user.org_id,contractId,b.clause_ref??null,b.clause_title??null,b.clause_text??null,b.category??null]);res.status(201).json({success:true,data:rows[0]});}));
contractsRouter.get('/variations/list',authorize('contracts','view'),asyncHandler(async(_req,res)=>{const rows=await query(`select v.*,p.project_code,c.contract_value from variations v join projects p on p.id=v.project_id join contracts c on c.id=v.contract_id order by v.created_at desc limit 500`);res.json({success:true,data:rows});}));
contractsRouter.post('/variations',authorize('contracts','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const b=variationSchema.parse(req.body);const rows=await query(`insert into variations(org_id,project_id,contract_id,variation_no,description,initiated_by,reason,cost_impact,time_impact_days,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'proposed') returning *`,[req.user.org_id,b.project_id,b.contract_id,b.variation_no,b.description,req.user.id,b.reason??null,b.cost_impact,b.time_impact_days]);res.status(201).json({success:true,data:rows[0]});}));
contractsRouter.get('/variations/:id',authorize('contracts','view'),asyncHandler(async(req,res)=>{const variationId=parseId(req.params.id);const variation=(await query(`select v.*,p.project_code,c.contract_value from variations v join projects p on p.id=v.project_id join contracts c on c.id=v.contract_id where v.id=$1`,[variationId]))[0];if(!variation)throw new AppError(404,'Variation not found');const lines=await query(`select * from variation_boq_lines where variation_id=$1 order by id`,[variationId]);res.json({success:true,data:{variation,lines}});}));
contractsRouter.post('/variations/:id/lines',authorize('contracts','create'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const variationId=parseId(req.params.id);const b=lineSchema.parse(req.body);const rows=await query(`insert into variation_boq_lines(org_id,variation_id,project_boq_item_id,description,unit_of_measure,quantity,unit_rate,action) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[req.user.org_id,variationId,b.project_boq_item_id??null,b.description,b.unit_of_measure,b.quantity,b.unit_rate,b.action]);res.status(201).json({success:true,data:rows[0]});}));
contractsRouter.post('/variations/:id/submit-approval',authorize('contracts','approve'),asyncHandler(async(req,res)=>{if(!req.user)throw new AppError(401,'Authentication required');const variationId=parseId(req.params.id);const client=await getClient();try{await client.query('begin');const v=(await client.query(`select * from variations where id=$1 for update`,[variationId])).rows[0];if(!v)throw new AppError(404,'Variation not found');if(v.status!=='proposed')throw new AppError(409,'Only proposed variations can be submitted');const approval=await createApprovalInstance(client,{org_id:req.user.org_id,module:'variation',record_id:variationId,amount:String(v.cost_impact).replace(/^-/,'') /* DOA routes on the absolute value (omissions); exact decimal string, no float conversion */,currency_id:(await client.query(`select currency_id from contracts where id=$1`,[v.contract_id])).rows[0]?.currency_id??null,initiated_by:req.user.id});await client.query(`update variations set status='under_review',approval_instance_id=$2,updated_at=now() where id=$1`,[variationId,approval.id]);await client.query('commit');res.json({success:true,data:{approval}});}catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}}));

// GC-15 (migration 048): client path after internal approval. Only a client-agreed valuation changes the
// execution BOQ (revised_* / new variation items) and the project's current contract value (STEP09).
contractsRouter.post('/variations/:id/client-submission',authorize('contracts','create'),asyncHandler(async(req,res)=>{
  const variationId=parseId(req.params.id);
  const b=z.object({submitted_on:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),reference:z.string().trim().min(3).max(500)}).parse(req.body);
  const v=(await query<any>(`select status,client_status from variations where id=$1`,[variationId]))[0];
  if(!v)throw new AppError(404,'Variation not found');
  if(v.status!=='approved'||v.client_status!=='not_submitted')throw new AppError(409,'Only internally approved, not yet submitted variations can be submitted to the client');
  const [r]=await query(`update variations set client_status='submitted',client_submitted_on=$2,client_submission_reference=$3,updated_at=now() where id=$1 returning *`,[variationId,b.submitted_on,b.reference]);
  res.json({success:true,data:r});
}));
contractsRouter.post('/variations/:id/client-decision',authorize('contracts','create'),asyncHandler(async(req,res)=>{
  const variationId=parseId(req.params.id);
  const b=z.object({decision:z.enum(['agreed','rejected']),decided_on:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),reference:z.string().trim().min(3).max(500),agreed_amount:z.number().optional(),agreed_time_days:z.number().int().optional()}).parse(req.body);
  const client=await getClient();
  try{
    await client.query('begin');
    const v=(await client.query(`select * from variations where id=$1 for update`,[variationId])).rows[0];
    if(!v)throw new AppError(404,'Variation not found');
    if(v.client_status!=='submitted')throw new AppError(409,'Only variations submitted to the client can be decided');
    const r=(await client.query(`update variations set client_status=$2,client_decided_on=$3,client_decision_reference=$4,agreed_amount=$5,agreed_time_days=$6,updated_at=now() where id=$1 returning *`,
      [variationId,b.decision,b.decided_on,b.reference,b.decision==='agreed'?(b.agreed_amount??null):null,b.decision==='agreed'?(b.agreed_time_days??null):null])).rows[0];
    if(b.decision==='agreed'){
      const lines=(await client.query(`select id,project_boq_item_id from variation_boq_lines where variation_id=$1 order by id`,[variationId])).rows;
      // All quantity/amount arithmetic stays in PostgreSQL NUMERIC (no JS float conversion of money).
      for(const l of lines){
        if(l.project_boq_item_id){
          await client.query(`update project_boq b set revised_quantity=coalesce(b.revised_quantity,b.contract_quantity)+(case when l.action='omit' then -l.quantity else l.quantity end),
              revised_amount=coalesce(b.revised_amount,b.contract_amount)+(case when l.action='omit' then -l.amount else l.amount end),updated_at=now()
            from variation_boq_lines l where l.id=$1 and b.id=l.project_boq_item_id`,[l.id]);
        }else{
          await client.query(`insert into project_boq(org_id,project_id,item_no,description,unit_of_measure,contract_quantity,contract_unit_rate,revised_quantity,revised_amount,is_locked,source_variation_id)
            select $1,$2,$3,l.description,l.unit_of_measure,0,l.unit_rate,l.quantity,l.amount,true,$4 from variation_boq_lines l where l.id=$5`,[v.org_id,v.project_id,`V${v.id}-${l.id}`.slice(0,20),v.id,l.id]);
        }
      }
      await client.query(`update projects set current_contract_value=coalesce(current_contract_value,original_contract_value,0)+$2,updated_at=now() where id=$1`,[v.project_id,r.agreed_amount]);
      await client.query(`update variations set applied_at=now() where id=$1`,[variationId]);
    }
    await client.query('commit');
    res.json({success:true,data:r});
  }catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);}
}));
