import { Router } from 'express';
import { z } from 'zod';
import { query, getClient, releaseClient } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';

export const crmRouter = Router();
const id = z.number().int().positive();
const leadSchema = z.object({
  lead_name:z.string().min(2).max(200), client_id:id.optional().nullable(), source:z.enum(['referral','tender','direct','marketing','other']).optional().nullable(),
  project_type:z.enum(['fit_out','finishing','construction','design_build']).optional().nullable(), estimated_value:z.number().nonnegative().optional().nullable(), currency_id:id.optional().nullable(),
  owner_id:id.optional(), expected_close_date:z.string().optional().nullable(), notes:z.string().optional().nullable()
});
const activitySchema = z.object({ activity_type:z.enum(['call','meeting','site_visit','email','other']), activity_date:z.string().optional(), notes:z.string().optional().nullable(), next_action_date:z.string().optional().nullable() });
const opportunitySchema = z.object({ opportunity_name:z.string().min(2).max(200), estimated_value:z.number().nonnegative().optional().nullable(), currency_id:id.optional().nullable(), probability_percent:z.number().min(0).max(100).optional().nullable() });

crmRouter.get('/leads',authorize('crm','view'),asyncHandler(async (_req,res)=>{ const rows=await query(`select l.*,c.client_name,u.full_name owner_name from leads l left join clients c on c.id=l.client_id join users u on u.id=l.owner_id order by l.created_at desc limit 500`); res.json({success:true,data:rows}); }));
crmRouter.get('/leads/:leadId',authorize('crm','view'),asyncHandler(async(req,res)=>{ const leadId=Number(req.params.leadId); const lead=(await query(`select l.*,c.client_name,u.full_name owner_name from leads l left join clients c on c.id=l.client_id join users u on u.id=l.owner_id where l.id=$1`,[leadId]))[0]; if(!lead) throw new AppError(404,'Lead not found'); const activities=await query(`select la.*,u.full_name performed_by_name from lead_activities la join users u on u.id=la.performed_by where la.lead_id=$1 order by la.activity_date desc`,[leadId]); const opportunities=await query(`select * from opportunities where lead_id=$1 order by created_at desc`,[leadId]); res.json({success:true,data:{lead,activities,opportunities}}); }));
crmRouter.post('/leads',authorize('crm','create'),asyncHandler(async(req,res)=>{ if(!req.user) throw new AppError(401,'Authentication required'); const b=leadSchema.parse(req.body); const ownerId=b.owner_id??req.user.id; const rows=await query(`insert into leads(org_id,lead_name,client_id,source,project_type,estimated_value,currency_id,stage,owner_id,expected_close_date,notes,created_by) values($1,$2,$3,$4,$5,$6,$7,'new',$8,$9,$10,$11) returning *`,[req.user.org_id,b.lead_name,b.client_id??null,b.source??null,b.project_type??null,b.estimated_value??null,b.currency_id??null,ownerId,b.expected_close_date??null,b.notes??null,req.user.id]); res.status(201).json({success:true,data:rows[0]}); }));
crmRouter.patch('/leads/:leadId',authorize('crm','edit'),asyncHandler(async(req,res)=>{ const leadId=Number(req.params.leadId); if(!Number.isInteger(leadId)||leadId<=0)throw new AppError(400,'Invalid lead id'); const b=leadSchema.partial().extend({stage:z.enum(['new','qualified','proposal','won','lost']).optional()}).parse(req.body); const current=(await query<any>('select * from leads where id=$1',[leadId]))[0]; if(!current)throw new AppError(404,'Lead not found'); const transitions:Record<string,string[]>={new:['qualified','lost'],qualified:['proposal','lost'],proposal:['won','lost'],won:[],lost:[]}; if(b.stage&&b.stage!==current.stage&&!(transitions[current.stage]||[]).includes(b.stage))throw new AppError(409,`Invalid lead transition ${current.stage} -> ${b.stage}`); if(['won','lost'].includes(current.stage)&&Object.keys(b).some(k=>k!=='stage'))throw new AppError(409,'Finalized lead is immutable'); const rows=await query(`update leads set lead_name=coalesce($2,lead_name),client_id=coalesce($3,client_id),source=coalesce($4,source),project_type=coalesce($5,project_type),estimated_value=coalesce($6,estimated_value),currency_id=coalesce($7,currency_id),stage=coalesce($8,stage),owner_id=coalesce($9,owner_id),expected_close_date=coalesce($10,expected_close_date),notes=coalesce($11,notes),updated_at=now() where id=$1 returning *`,[leadId,b.lead_name??null,b.client_id??null,b.source??null,b.project_type??null,b.estimated_value??null,b.currency_id??null,b.stage??null,b.owner_id??null,b.expected_close_date??null,b.notes??null]); res.json({success:true,data:rows[0]}); }));
crmRouter.post('/leads/:leadId/activities',authorize('crm','create'),asyncHandler(async(req,res)=>{ if(!req.user) throw new AppError(401,'Authentication required'); const leadId=Number(req.params.leadId); const b=activitySchema.parse(req.body); const rows=await query(`insert into lead_activities(org_id,lead_id,activity_type,activity_date,performed_by,notes,next_action_date) values($1,$2,$3,coalesce($4::timestamptz,now()),$5,$6,$7) returning *`,[req.user.org_id,leadId,b.activity_type,b.activity_date??null,req.user.id,b.notes??null,b.next_action_date??null]); res.status(201).json({success:true,data:rows[0]}); }));
crmRouter.get('/opportunities',authorize('crm','view'),asyncHandler(async(_req,res)=>{ const rows=await query(`select o.*,l.lead_name,c.client_name from opportunities o join leads l on l.id=o.lead_id left join clients c on c.id=l.client_id order by o.created_at desc limit 500`); res.json({success:true,data:rows}); }));
crmRouter.post('/leads/:leadId/opportunities',authorize('crm','create'),asyncHandler(async(req,res)=>{ const leadId=Number(req.params.leadId); const b=opportunitySchema.parse(req.body); const rows=await query(`insert into opportunities(org_id,lead_id,opportunity_name,estimated_value,currency_id,probability_percent,status,created_by) values((select org_id from leads where id=$1),$1,$2,$3,$4,$5,'open',$6) returning *`,[leadId,b.opportunity_name,b.estimated_value??null,b.currency_id??null,b.probability_percent??null,req.user?.id??null]); if(!rows[0]) throw new AppError(404,'Lead not found'); res.status(201).json({success:true,data:rows[0]}); }));
crmRouter.patch('/opportunities/:opportunityId',authorize('crm','edit'),asyncHandler(async(req,res)=>{ const opportunityId=Number(req.params.opportunityId); if(!Number.isInteger(opportunityId)||opportunityId<=0)throw new AppError(400,'Invalid opportunity id'); const b=opportunitySchema.partial().extend({status:z.enum(['open','lost']).optional()}).parse(req.body); const current=(await query<any>('select * from opportunities where id=$1',[opportunityId]))[0]; if(!current)throw new AppError(404,'Opportunity not found'); if(current.status!=='open')throw new AppError(409,'Finalized opportunity is immutable'); const rows=await query(`update opportunities set opportunity_name=coalesce($2,opportunity_name),estimated_value=coalesce($3,estimated_value),currency_id=coalesce($4,currency_id),probability_percent=coalesce($5,probability_percent),status=coalesce($6,status),updated_at=now() where id=$1 returning *`,[opportunityId,b.opportunity_name??null,b.estimated_value??null,b.currency_id??null,b.probability_percent??null,b.status??null]); res.json({success:true,data:rows[0]}); }));
crmRouter.post('/opportunities/:opportunityId/convert-to-tender',authorize('crm','edit'),asyncHandler(async(req,res)=>{ if(!req.user) throw new AppError(401,'Authentication required'); const opportunityId=Number(req.params.opportunityId); const b=z.object({tender_ref:z.string().min(2).max(50),tender_title:z.string().min(2).max(200),tender_type:z.enum(['public','private','invited']).default('private'),submission_deadline:z.string().optional().nullable(),bond_required:z.boolean().default(false),bond_amount:z.number().nonnegative().optional().nullable(),estimated_value:z.number().nonnegative().optional().nullable(),currency_id:id.optional().nullable()}).parse(req.body); const client=await getClient(); try{ await client.query('begin'); const opp=(await client.query(`select o.*,l.client_id,l.org_id from opportunities o join leads l on l.id=o.lead_id where o.id=$1 for update`,[opportunityId])).rows[0]; if(!opp) throw new AppError(404,'Opportunity not found'); if(opp.status!=='open') throw new AppError(409,'Only open opportunities can be converted'); const tender=(await client.query(`insert into tenders(org_id,opportunity_id,client_id,tender_ref,tender_title,tender_type,submission_deadline,bond_required,bond_amount,estimated_value,currency_id,assigned_estimator_id,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,coalesce($10::numeric,$11::numeric),$12,$13,'in_progress',$14) returning *`,[opp.org_id,opp.id,opp.client_id,b.tender_ref,b.tender_title,b.tender_type,b.submission_deadline??null,b.bond_required,b.bond_amount??null,b.estimated_value??null,opp.estimated_value,b.currency_id??opp.currency_id,req.user.id,req.user.id])).rows[0]; await client.query(`update opportunities set status='converted',converts_to_tender_id=$2,updated_at=now() where id=$1`,[opp.id,tender.id]); await client.query('commit'); res.status(201).json({success:true,data:tender}); }catch(e){await client.query('rollback');throw e;}finally{await releaseClient(client);} }));
