import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { ReferenceSelect } from '../components/ReferenceSelect';

export function Planning() {
  const [projectId,setProjectId]=useState('');
  const [activities,setActivities]=useState<any[]>([]); const [baselines,setBaselines]=useState<any[]>([]); const [relationships,setRelationships]=useState<any[]>([]); const [milestones,setMilestones]=useState<any[]>([]); const [cpm,setCpm]=useState<any>(null); const [error,setError]=useState('');
  const [activityForm,setActivityForm]=useState({activity_id_ext:'',activity_name:'',planned_start:'',planned_finish:'',planned_duration_days:'0',baseline_id:''});
  const [baselineName,setBaselineName]=useState(''); const [milestoneName,setMilestoneName]=useState('');
  const [rel,setRel]=useState({predecessor_activity_id:'',successor_activity_id:'',relationship_type:'FS',lag_days:'0'});
  const avg=useMemo(()=>activities.length?activities.reduce((s,a)=>s+Number(a.percent_complete||0),0)/activities.length:0,[activities]);

  async function load(pid=projectId){setError('');const suffix=pid?`?project_id=${Number(pid)}`:'';try{const [a,b,r,m]=await Promise.all([api.get(`/planning/activities${suffix}`),api.get(`/planning/baselines${suffix}`),api.get(`/planning/relationships${suffix}`),api.get(`/planning/milestones${suffix}`)]);setActivities(a.data);setBaselines(b.data);setRelationships(r.data);setMilestones(m.data);}catch(e:any){setError(e.message)}}
  useEffect(()=>{load('')},[]);
  async function createBaseline(){if(!projectId||!baselineName)return;await api.post('/planning/baselines',{project_id:Number(projectId),baseline_name:baselineName,is_current:baselines.length===0});setBaselineName('');await load()}
  async function makeCurrent(id:number){await api.patch(`/planning/baselines/${id}/current`,{});await load()}
  async function createActivity(){if(!projectId||!activityForm.activity_name)return;await api.post('/planning/activities',{project_id:Number(projectId),activity_id_ext:activityForm.activity_id_ext||undefined,activity_name:activityForm.activity_name,planned_start:activityForm.planned_start||undefined,planned_finish:activityForm.planned_finish||undefined,planned_duration_days:Number(activityForm.planned_duration_days||0),baseline_id:activityForm.baseline_id?Number(activityForm.baseline_id):undefined});setActivityForm({activity_id_ext:'',activity_name:'',planned_start:'',planned_finish:'',planned_duration_days:'0',baseline_id:''});await load()}
  async function updateProgress(id:number,current:any){const raw=prompt('Percent complete',String(current??0));if(raw===null)return;const pct=Number(raw);if(!Number.isFinite(pct)||pct<0||pct>100)return alert('Progress must be 0-100');await api.patch(`/planning/activities/${id}/progress`,{percent_complete:pct});await load()}
  async function createRelationship(){if(!projectId||!rel.predecessor_activity_id||!rel.successor_activity_id)return;await api.post('/planning/relationships',{project_id:Number(projectId),predecessor_activity_id:Number(rel.predecessor_activity_id),successor_activity_id:Number(rel.successor_activity_id),relationship_type:rel.relationship_type,lag_days:Number(rel.lag_days||0)});await load()}
  async function createMilestone(){if(!projectId||!milestoneName)return;await api.post('/planning/milestones',{project_id:Number(projectId),milestone_name:milestoneName});setMilestoneName('');await load()}
  async function runCpm(){if(!projectId)return;try{const r=await api.get(`/planning/cpm?project_id=${Number(projectId)}`);setCpm(r.data);setError('')}catch(e:any){setError(e.message)}}

  return <section className="page"><h1>Planning & Scheduling</h1><p className="muted">Operational schedule register, baselines, relationships, progress, milestones and CPM.</p>
    {error&&<div className="panel"><strong>Error:</strong> {error}</div>}
    <div className="panel"><h2>Project Scope</h2><div className="form-row"><ReferenceSelect kind="projects" value={projectId} onChange={setProjectId} placeholder="Project"/><button onClick={()=>load()}>Load Project</button><button onClick={runCpm}>Calculate CPM</button></div></div>
    <div className="cards-grid"><div className="metric-card"><span>Baselines</span><strong>{baselines.length}</strong></div><div className="metric-card"><span>Activities</span><strong>{activities.length}</strong></div><div className="metric-card"><span>Progress</span><strong>{avg.toFixed(1)}%</strong></div><div className="metric-card"><span>Relationships</span><strong>{relationships.length}</strong></div></div>
    <div className="panel"><h2>Baselines</h2><div className="form-row"><input value={baselineName} onChange={e=>setBaselineName(e.target.value)} placeholder="Baseline name"/><button onClick={createBaseline}>Create</button></div><table><thead><tr><th>Name</th><th>Date</th><th>Current</th><th>Action</th></tr></thead><tbody>{baselines.map(b=><tr key={b.id}><td>{b.baseline_name}</td><td>{b.baseline_date}</td><td>{b.is_current?'Yes':'No'}</td><td>{!b.is_current&&<button onClick={()=>makeCurrent(b.id)}>Make Current</button>}</td></tr>)}</tbody></table></div>
    <div className="panel"><h2>Activities</h2><div className="form-row"><input value={activityForm.activity_id_ext} onChange={e=>setActivityForm({...activityForm,activity_id_ext:e.target.value})} placeholder="Activity ID"/><input value={activityForm.activity_name} onChange={e=>setActivityForm({...activityForm,activity_name:e.target.value})} placeholder="Activity name"/><input type="date" value={activityForm.planned_start} onChange={e=>setActivityForm({...activityForm,planned_start:e.target.value})}/><input type="date" value={activityForm.planned_finish} onChange={e=>setActivityForm({...activityForm,planned_finish:e.target.value})}/><input type="number" min="0" value={activityForm.planned_duration_days} onChange={e=>setActivityForm({...activityForm,planned_duration_days:e.target.value})} placeholder="Duration"/><select value={activityForm.baseline_id} onChange={e=>setActivityForm({...activityForm,baseline_id:e.target.value})}><option value="">No baseline</option>{baselines.map(b=><option key={b.id} value={b.id}>{b.baseline_name}</option>)}</select><button onClick={createActivity}>Add Activity</button></div><table><thead><tr><th>ID</th><th>Name</th><th>Baseline</th><th>Planned</th><th>Duration</th><th>%</th><th>Action</th></tr></thead><tbody>{activities.map(a=><tr key={a.id}><td>{a.activity_id_ext||a.id}</td><td>{a.activity_name}</td><td>{a.baseline_name||'-'}</td><td>{a.planned_start||'-'} → {a.planned_finish||'-'}</td><td>{a.planned_duration_days??'-'}</td><td>{a.percent_complete}%</td><td><button onClick={()=>updateProgress(a.id,a.percent_complete)}>Progress</button></td></tr>)}</tbody></table></div>
    <div className="panel"><h2>Relationships</h2><div className="form-row"><select value={rel.predecessor_activity_id} onChange={e=>setRel({...rel,predecessor_activity_id:e.target.value})}><option value="">Predecessor</option>{activities.map(a=><option key={a.id} value={a.id}>{a.activity_id_ext||a.id} — {a.activity_name}</option>)}</select><select value={rel.successor_activity_id} onChange={e=>setRel({...rel,successor_activity_id:e.target.value})}><option value="">Successor</option>{activities.map(a=><option key={a.id} value={a.id}>{a.activity_id_ext||a.id} — {a.activity_name}</option>)}</select><select value={rel.relationship_type} onChange={e=>setRel({...rel,relationship_type:e.target.value})}>{['FS','SS','FF','SF'].map(x=><option key={x}>{x}</option>)}</select><input type="number" value={rel.lag_days} onChange={e=>setRel({...rel,lag_days:e.target.value})} placeholder="Lag"/><button onClick={createRelationship}>Add Relationship</button></div><table><thead><tr><th>Predecessor</th><th>Type</th><th>Lag</th><th>Successor</th><th></th></tr></thead><tbody>{relationships.map(r=><tr key={r.id}><td>{r.predecessor_code||r.predecessor_activity_id}</td><td>{r.relationship_type}</td><td>{r.lag_days}</td><td>{r.successor_code||r.successor_activity_id}</td><td><button onClick={async()=>{await api.delete(`/planning/relationships/${r.id}`);await load()}}>Delete</button></td></tr>)}</tbody></table></div>
    <div className="panel"><h2>Milestones</h2><div className="form-row"><input value={milestoneName} onChange={e=>setMilestoneName(e.target.value)} placeholder="Milestone name"/><button onClick={createMilestone}>Add Milestone</button></div><table><thead><tr><th>Name</th><th>Planned</th><th>Actual</th><th>Contractual</th></tr></thead><tbody>{milestones.map(m=><tr key={m.id}><td>{m.milestone_name}</td><td>{m.planned_date||'-'}</td><td>{m.actual_date||'-'}</td><td>{m.is_contractual?'Yes':'No'}</td></tr>)}</tbody></table></div>
    {cpm&&<div className="panel"><h2>CPM Analysis</h2><p>Project Duration: <strong>{cpm.project_duration_days} days</strong></p><p>Critical Path IDs: {cpm.critical_path.join(' → ')||'None'}</p><table><thead><tr><th>Activity</th><th>ES</th><th>EF</th><th>LS</th><th>LF</th><th>TF</th><th>FF</th><th>Critical</th></tr></thead><tbody>{cpm.activities.map((a:any)=><tr key={a.id}><td>{a.activity_id||a.id} — {a.name}</td><td>{a.early_start_day}</td><td>{a.early_finish_day}</td><td>{a.late_start_day}</td><td>{a.late_finish_day}</td><td>{a.total_float_days}</td><td>{a.free_float_days}</td><td>{a.is_critical?'Yes':'No'}</td></tr>)}</tbody></table></div>}
  </section>;
}
