import { useEffect, useState } from 'react';
import { apiGet, apiPost } from '../lib/api';

type Any=Record<string,any>; type Api<T>={success:boolean;data:T};
const n=(v:any)=>Number(v);
export function Procurement(){
 const[po,setPo]=useState<Any[]>([]),[poLines,setPoLines]=useState<Any[]>([]),[vi,setVi]=useState<Any[]>([]),[mr,setMr]=useState<Any[]>([]),[rfq,setRfq]=useState<Any[]>([]),[grns,setGrns]=useState<Any[]>([]),[refs,setRefs]=useState<any>({projects:[],vendors:[],costCodes:[],currencies:[],warehouses:[],items:[]}),[msg,setMsg]=useState('');
 const[m,setM]=useState<any>({project_id:'',mr_no:'',required_date:'',item_description:'',unit_of_measure:'ea',quantity:1});
 const[r,setR]=useState<any>({project_id:'',mr_id:'',rfq_ref:'',due_date:'',vendor_id:''});
 const[q,setQ]=useState<any>({rfq_id:'',vendor_id:'',quotation_ref:'',total_amount:'',currency_id:''});
 const[p,setP]=useState<any>({project_id:'',vendor_id:'',mr_id:'',cost_code_id:'',po_ref:'',currency_id:'',item_description:'',unit_of_measure:'ea',quantity:1,unit_rate:0});
 const[g,setG]=useState<any>({po_id:'',project_id:'',warehouse_id:'',grn_no:'',po_line_id:'',inventory_item_id:'',quantity_received:1,quantity_accepted:1,quantity_rejected:0});
 const[i,setI]=useState<any>({vendor_id:'',project_id:'',po_id:'',invoice_no:'',invoice_date:new Date().toISOString().slice(0,10),amount:'',tax_amount:0,currency_id:'',matched_grn_id:''});
 async function load(){const[a,b,c,d,e,f]=await Promise.all([apiGet<Api<Any[]>>('/procurement/purchase-orders'),apiGet<Api<Any[]>>('/procurement/vendor-invoices'),apiGet<Api<Any[]>>('/procurement/material-requisitions'),apiGet<Api<Any[]>>('/procurement/rfqs'),apiGet<Api<Any[]>>('/procurement/grns'),apiGet<Api<any>>('/procurement/reference-data')]);setPo(a.data);setVi(b.data);setMr(c.data);setRfq(d.data);setGrns(e.data);setRefs(f.data)}
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]); async function run(fn:()=>Promise<any>,ok:string){try{setMsg('');await fn();await load();setMsg(ok)}catch(e:any){setMsg(e.message)}}
 async function makeMr(){await run(()=>apiPost('/procurement/material-requisitions',{project_id:n(m.project_id),mr_no:m.mr_no,required_date:m.required_date||null,lines:[{item_description:m.item_description,unit_of_measure:m.unit_of_measure,quantity:n(m.quantity)}]}),'MR created')}
 async function makeRfq(){await run(()=>apiPost('/procurement/rfqs',{project_id:n(r.project_id),mr_id:r.mr_id?n(r.mr_id):null,rfq_ref:r.rfq_ref,due_date:r.due_date||null,vendor_ids:r.vendor_id?[n(r.vendor_id)]:[]}),'RFQ created')}
 async function makeQuote(){await run(()=>apiPost(`/procurement/rfqs/${q.rfq_id}/vendor-quotations`,{vendor_id:n(q.vendor_id),quotation_ref:q.quotation_ref||null,total_amount:n(q.total_amount),currency_id:n(q.currency_id)}),'Quotation recorded')}
 async function makePo(){await run(()=>apiPost('/procurement/purchase-orders',{project_id:n(p.project_id),vendor_id:n(p.vendor_id),mr_id:p.mr_id?n(p.mr_id):null,cost_code_id:n(p.cost_code_id),po_ref:p.po_ref,currency_id:n(p.currency_id),lines:[{item_description:p.item_description,unit_of_measure:p.unit_of_measure,quantity:n(p.quantity),unit_rate:n(p.unit_rate)}]}),'PO created')}
 async function choosePoForGrn(id:string){setG({...g,po_id:id,po_line_id:''});if(!id)return;try{const x=await apiGet<Api<any>>(`/procurement/purchase-orders/${id}/details`);setPoLines(x.data.lines||[]);setG((v:any)=>({...v,po_id:id,project_id:x.data.po.project_id,po_line_id:x.data.lines[0]?.id||''}))}catch(e:any){setMsg(e.message)}}
 async function makeGrn(){await run(()=>apiPost(`/procurement/purchase-orders/${g.po_id}/grns`,{project_id:n(g.project_id),warehouse_id:n(g.warehouse_id),grn_no:g.grn_no,lines:[{po_line_id:n(g.po_line_id),inventory_item_id:n(g.inventory_item_id),quantity_received:n(g.quantity_received),quantity_accepted:n(g.quantity_accepted),quantity_rejected:n(g.quantity_rejected)}]}),'GRN created')}
 async function makeInvoice(){await run(()=>apiPost('/procurement/vendor-invoices',{vendor_id:n(i.vendor_id),project_id:n(i.project_id),po_id:n(i.po_id),invoice_no:i.invoice_no,invoice_date:i.invoice_date,amount:n(i.amount),tax_amount:n(i.tax_amount),currency_id:n(i.currency_id),matched_grn_id:i.matched_grn_id?n(i.matched_grn_id):null}),'Invoice created')}
 const projOpts=refs.projects.map((x:any)=><option key={x.id} value={x.id}>{x.project_code} — {x.project_name}</option>),vendorOpts=refs.vendors.map((x:any)=><option key={x.id} value={x.id}>{x.vendor_name}</option>),curOpts=refs.currencies.map((x:any)=><option key={x.id} value={x.id}>{x.code}</option>);
 return <section className="page-stack"><header className="page-header"><div><p className="eyebrow">Procure-to-Pay</p><h1>Procurement Control</h1><p>Operational MR → RFQ → Quote → PO → GRN → Invoice → 3-Way Match → Approval.</p></div></header>{msg&&<div className="notice">{msg}</div>}
 <div className="panel"><h2>Create Material Requisition</h2><div className="form-row"><select value={m.project_id} onChange={e=>setM({...m,project_id:e.target.value})}><option value="">Project</option>{projOpts}</select><input placeholder="MR No." value={m.mr_no} onChange={e=>setM({...m,mr_no:e.target.value})}/><input type="date" value={m.required_date} onChange={e=>setM({...m,required_date:e.target.value})}/><input placeholder="Item" value={m.item_description} onChange={e=>setM({...m,item_description:e.target.value})}/><input placeholder="UOM" value={m.unit_of_measure} onChange={e=>setM({...m,unit_of_measure:e.target.value})}/><input type="number" min="0.001" step="0.001" value={m.quantity} onChange={e=>setM({...m,quantity:e.target.value})}/><button onClick={makeMr} disabled={!m.project_id||!m.mr_no||!m.item_description}>Create MR</button></div></div>
 <div className="panel"><h2>Create RFQ / Record Quotation</h2><div className="form-row"><select value={r.project_id} onChange={e=>setR({...r,project_id:e.target.value})}><option value="">Project</option>{projOpts}</select><select value={r.mr_id} onChange={e=>setR({...r,mr_id:e.target.value})}><option value="">Optional MR</option>{mr.map(x=><option key={x.id} value={x.id}>{x.mr_no}</option>)}</select><input placeholder="RFQ Ref" value={r.rfq_ref} onChange={e=>setR({...r,rfq_ref:e.target.value})}/><input type="date" value={r.due_date} onChange={e=>setR({...r,due_date:e.target.value})}/><select value={r.vendor_id} onChange={e=>setR({...r,vendor_id:e.target.value})}><option value="">Invite vendor</option>{vendorOpts}</select><button onClick={makeRfq} disabled={!r.project_id||!r.rfq_ref}>Create RFQ</button></div><div className="form-row"><select value={q.rfq_id} onChange={e=>setQ({...q,rfq_id:e.target.value})}><option value="">RFQ</option>{rfq.map(x=><option key={x.id} value={x.id}>{x.rfq_ref}</option>)}</select><select value={q.vendor_id} onChange={e=>setQ({...q,vendor_id:e.target.value})}><option value="">Vendor</option>{vendorOpts}</select><input placeholder="Quote ref" value={q.quotation_ref} onChange={e=>setQ({...q,quotation_ref:e.target.value})}/><input type="number" placeholder="Total" value={q.total_amount} onChange={e=>setQ({...q,total_amount:e.target.value})}/><select value={q.currency_id} onChange={e=>setQ({...q,currency_id:e.target.value})}><option value="">Currency</option>{curOpts}</select><button onClick={makeQuote} disabled={!q.rfq_id||!q.vendor_id||!q.total_amount||!q.currency_id}>Record Quote</button></div></div>
 <div className="panel"><h2>Create Purchase Order</h2><div className="form-row"><select value={p.project_id} onChange={e=>setP({...p,project_id:e.target.value})}><option value="">Project</option>{projOpts}</select><select value={p.vendor_id} onChange={e=>setP({...p,vendor_id:e.target.value})}><option value="">Vendor</option>{vendorOpts}</select><select value={p.cost_code_id} onChange={e=>setP({...p,cost_code_id:e.target.value})}><option value="">Cost code</option>{refs.costCodes.filter((x:any)=>!x.project_id||String(x.project_id)===String(p.project_id)).map((x:any)=><option key={x.id} value={x.id}>{x.code} — {x.description}</option>)}</select><input placeholder="PO Ref" value={p.po_ref} onChange={e=>setP({...p,po_ref:e.target.value})}/><select value={p.currency_id} onChange={e=>setP({...p,currency_id:e.target.value})}><option value="">Currency</option>{curOpts}</select><input placeholder="Item" value={p.item_description} onChange={e=>setP({...p,item_description:e.target.value})}/><input type="number" step="0.001" value={p.quantity} onChange={e=>setP({...p,quantity:e.target.value})}/><input type="number" step="0.01" value={p.unit_rate} onChange={e=>setP({...p,unit_rate:e.target.value})}/><button onClick={makePo} disabled={!p.project_id||!p.vendor_id||!p.cost_code_id||!p.po_ref||!p.currency_id||!p.item_description}>Create PO</button></div></div>
 <div className="panel"><h2>Purchase Orders</h2><div className="table-wrap"><table><thead><tr><th>PO</th><th>Project</th><th>Vendor</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{po.map(x=><tr key={x.id}><td>{x.po_ref}</td><td>{x.project_code}</td><td>{x.vendor_name}</td><td>{x.total_amount} {x.currency_code}</td><td>{x.status}</td><td>{x.status==='draft'&&<button onClick={()=>run(()=>apiPost(`/procurement/purchase-orders/${x.id}/submit-approval`,{}),'PO submitted')}>Submit</button>}{x.status==='approved'&&<button onClick={()=>run(()=>apiPost(`/procurement/purchase-orders/${x.id}/issue`,{}),'PO issued')}>Issue</button>}</td></tr>)}</tbody></table></div></div>
 <div className="panel"><h2>GRN</h2><div className="form-row"><select value={g.po_id} onChange={e=>choosePoForGrn(e.target.value)}><option value="">Issued PO</option>{po.filter(x=>['issued','partially_delivered'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.po_ref}</option>)}</select><select value={g.warehouse_id} onChange={e=>setG({...g,warehouse_id:e.target.value})}><option value="">Warehouse</option>{refs.warehouses.map((x:any)=><option key={x.id} value={x.id}>{x.code}</option>)}</select><input placeholder="GRN No." value={g.grn_no} onChange={e=>setG({...g,grn_no:e.target.value})}/><select value={g.po_line_id} onChange={e=>setG({...g,po_line_id:e.target.value})}><option value="">PO line</option>{poLines.map(x=><option key={x.id} value={x.id}>{x.item_description} — {x.quantity} {x.unit_of_measure}</option>)}</select><select value={g.inventory_item_id} onChange={e=>setG({...g,inventory_item_id:e.target.value})}><option value="">Inventory item</option>{refs.items.map((x:any)=><option key={x.id} value={x.id}>{x.item_code} — {x.description}</option>)}</select><input type="number" step="0.001" value={g.quantity_received} onChange={e=>setG({...g,quantity_received:e.target.value})}/><input type="number" step="0.001" value={g.quantity_accepted} onChange={e=>setG({...g,quantity_accepted:e.target.value})}/><button onClick={makeGrn} disabled={!g.po_id||!g.warehouse_id||!g.grn_no||!g.po_line_id||!g.inventory_item_id}>Create GRN</button></div><div className="table-wrap"><table><thead><tr><th>GRN</th><th>PO</th><th>Project</th><th>Status</th><th>Action</th></tr></thead><tbody>{grns.map(x=><tr key={x.id}><td>{x.grn_no}</td><td>{x.po_ref}</td><td>{x.project_code}</td><td>{x.status}</td><td>{x.status==='draft'&&<button onClick={()=>run(()=>apiPost(`/procurement/grns/${x.id}/confirm`,{}),'GRN confirmed')}>Confirm</button>}</td></tr>)}</tbody></table></div></div>
 <div className="panel"><h2>Vendor Invoice & 3-Way Match</h2><div className="form-row"><select value={i.project_id} onChange={e=>setI({...i,project_id:e.target.value})}><option value="">Project</option>{projOpts}</select><select value={i.vendor_id} onChange={e=>setI({...i,vendor_id:e.target.value})}><option value="">Vendor</option>{vendorOpts}</select><select value={i.po_id} onChange={e=>setI({...i,po_id:e.target.value})}><option value="">PO</option>{po.map(x=><option key={x.id} value={x.id}>{x.po_ref}</option>)}</select><select value={i.matched_grn_id} onChange={e=>setI({...i,matched_grn_id:e.target.value})}><option value="">Confirmed GRN</option>{grns.filter(x=>x.status==='confirmed').map(x=><option key={x.id} value={x.id}>{x.grn_no}</option>)}</select><input placeholder="Invoice No." value={i.invoice_no} onChange={e=>setI({...i,invoice_no:e.target.value})}/><input type="date" value={i.invoice_date} onChange={e=>setI({...i,invoice_date:e.target.value})}/><input type="number" placeholder="Amount" value={i.amount} onChange={e=>setI({...i,amount:e.target.value})}/><input type="number" placeholder="Tax" value={i.tax_amount} onChange={e=>setI({...i,tax_amount:e.target.value})}/><select value={i.currency_id} onChange={e=>setI({...i,currency_id:e.target.value})}><option value="">Currency</option>{curOpts}</select><button onClick={makeInvoice} disabled={!i.project_id||!i.vendor_id||!i.po_id||!i.invoice_no||!i.amount||!i.currency_id}>Create Invoice</button></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Project</th><th>Vendor</th><th>Status</th><th>Action</th></tr></thead><tbody>{vi.map(x=><tr key={x.id}><td>{x.invoice_no}</td><td>{x.project_code}</td><td>{x.vendor_name}</td><td>{x.status}</td><td>{x.status==='received'&&<button onClick={()=>run(()=>apiPost(`/procurement/vendor-invoices/${x.id}/match`,{tolerance_amount:0}),'3-Way Match executed')}>3-Way Match</button>}{x.status==='matched'&&<button onClick={()=>run(()=>apiPost(`/procurement/vendor-invoices/${x.id}/submit-approval`,{}),'Invoice submitted')}>Submit</button>}</td></tr>)}</tbody></table></div></div>
 </section>
}
