import { useEffect, useState } from 'react';
import { apiGet, apiPost } from '../lib/api';

type Project = { id:number; project_code:string; project_name:string; project_type:string; status:string; location?:string; currency_code?:string };
type ApiResponse<T> = { success:boolean; data:T };
type RefData={clients:{id:number;client_name:string}[];currencies:{id:number;code:string;name:string}[]};

export function Projects(){
 const[rows,setRows]=useState<Project[]>([]);const[refs,setRefs]=useState<RefData>({clients:[],currencies:[]});const[msg,setMsg]=useState('');
 const[f,setF]=useState<any>({project_code:'',project_name:'',project_type:'fit_out',currency_id:0,client_id:'',status:'execution',location:''});
 async function load(){const[a,b]=await Promise.all([apiGet<ApiResponse<Project[]>>('/projects'),apiGet<ApiResponse<RefData>>('/projects/reference-data/options')]);setRows(a.data);setRefs(b.data);if(!f.currency_id&&b.data.currencies[0])setF((x:any)=>({...x,currency_id:b.data.currencies[0].id}))}
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
 async function create(){try{setMsg('');await apiPost('/projects',{...f,currency_id:Number(f.currency_id),client_id:f.client_id?Number(f.client_id):undefined});setF((x:any)=>({...x,project_code:'',project_name:'',location:''}));await load();setMsg('Project created.')}catch(e:any){setMsg(e.message)}}
 return <section className="page-stack"><header className="page-header"><div><p className="eyebrow">Project Master</p><h1>Projects</h1><p>Create and manage the project register without SQL intervention.</p></div></header>{msg&&<div className="notice">{msg}</div>}
 <div className="panel"><h2>Create Project</h2><div className="form-row"><input placeholder="Project code" value={f.project_code} onChange={e=>setF({...f,project_code:e.target.value})}/><input placeholder="Project name" value={f.project_name} onChange={e=>setF({...f,project_name:e.target.value})}/><select value={f.project_type} onChange={e=>setF({...f,project_type:e.target.value})}><option value="fit_out">Fit-out</option><option value="finishing">Finishing</option><option value="construction">Construction</option><option value="design_build">Design & Build</option></select><select value={f.currency_id} onChange={e=>setF({...f,currency_id:Number(e.target.value)})}>{refs.currencies.map(c=><option key={c.id} value={c.id}>{c.code}</option>)}</select><select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">No client</option>{refs.clients.map(c=><option key={c.id} value={c.id}>{c.client_name}</option>)}</select><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{['lead','tender','awarded','execution','closeout'].map(s=><option key={s}>{s}</option>)}</select><input placeholder="Location" value={f.location} onChange={e=>setF({...f,location:e.target.value})}/><button onClick={create} disabled={!f.project_code||!f.project_name||!f.currency_id}>Create Project</button></div></div>
 <div className="table-card"><table><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Status</th><th>Currency</th><th>Location</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.project_code}</td><td>{r.project_name}</td><td>{r.project_type}</td><td>{r.status}</td><td>{r.currency_code??'-'}</td><td>{r.location??'-'}</td></tr>)}{!rows.length&&<tr><td colSpan={6}>No projects yet.</td></tr>}</tbody></table></div></section>
}
