import { Router } from 'express';
import { z } from 'zod';
import { query } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';

export const technicalOfficeRouter = Router();
technicalOfficeRouter.use(authorize('technical_office', 'view'));
const parseId=(v:string)=>{const n=Number(v);if(!Number.isInteger(n)||n<=0)throw new AppError(400,'Invalid id');return n;};

const drawingSchema = z.object({project_id:z.number().int().positive(),drawing_no:z.string().min(1).max(50),title:z.string().min(1).max(255),discipline:z.string().max(50).optional(),revision:z.string().max(10).default('A'),document_id:z.number().int().positive().optional()});
const submittalSchema = z.object({project_id:z.number().int().positive(),submittal_no:z.string().min(1).max(30),type:z.enum(['material','shop_drawing','method_statement','sample','other']),description:z.string().min(1),reviewer_id:z.number().int().positive().optional(),due_date:z.string().optional(),document_id:z.number().int().positive().optional()});
const rfiSchema = z.object({project_id:z.number().int().positive(),rfi_no:z.string().min(1).max(30),subject:z.string().min(1).max(255),question:z.string().min(1),assigned_to:z.number().int().positive().optional(),cost_impact_flag:z.boolean().default(false),time_impact_flag:z.boolean().default(false),response_due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()});
const methodStatementSchema = z.object({project_id:z.number().int().positive(),activity_name:z.string().min(1).max(255),document_id:z.number().int().positive().optional()});

technicalOfficeRouter.get('/drawings',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query<any>(`select * from drawings where ($1::bigint=0 or project_id=$1) order by issued_date desc,id desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/drawings',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=drawingSchema.parse(req.body);const [r]=await query<any>(`insert into drawings(project_id,drawing_no,title,discipline,revision,status,document_id,issued_by) values($1,$2,$3,$4,$5,'for_review',$6,$7) returning *`,[b.project_id,b.drawing_no,b.title,b.discipline??null,b.revision,b.document_id??null,req.user!.id]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.patch('/drawings/:id/status',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({status:z.enum(['for_review','approved','approved_with_comments','rejected','superseded']),comment:z.string().trim().max(4000).optional()}).refine(v=>!['rejected','approved_with_comments'].includes(v.status)||(v.comment??'').length>=5,{message:'Review comments required (at least 5 characters)',path:['comment']}).parse(req.body);const current=(await query<any>(`select * from drawings where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Drawing not found');const allowed:Record<string,string[]>={for_review:['approved','approved_with_comments','rejected'],approved:['superseded'],approved_with_comments:['superseded'],rejected:['for_review'],superseded:[]};if(!(allowed[current.status]||[]).includes(b.status))throw new AppError(409,`Invalid drawing transition ${current.status} -> ${b.status}`);if(['approved','approved_with_comments','rejected'].includes(b.status)&&Number(current.issued_by)===req.user!.id)throw new AppError(403,'Segregation of duties: drawing issuer cannot review own drawing');const [r]=await query<any>(`update drawings set status=$2::varchar,review_comment=case when $2::varchar in ('approved','approved_with_comments','rejected') then $4::text else review_comment end,reviewed_by=case when $2::varchar in ('approved','approved_with_comments','rejected') then $3::bigint else reviewed_by end,reviewed_at=case when $2::varchar in ('approved','approved_with_comments','rejected') then now() else reviewed_at end,updated_at=now() where id=$1 returning *`,[id,b.status,req.user!.id,b.comment??null]);res.json({success:true,data:r});}));

technicalOfficeRouter.get('/submittals',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query<any>(`select * from submittals where ($1::bigint=0 or project_id=$1) order by submitted_date desc,id desc limit 200`,[projectId])});}));
technicalOfficeRouter.get('/submittals/:id',asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const sb=(await query<any>(`select * from submittals where id=$1 and org_id=$2`,[id,req.user!.org_id]))[0];if(!sb)throw new AppError(404,'Submittal not found');const reviews=await query<any>(`select * from submittal_reviews where submittal_id=$1 order by cycle`,[id]);res.json({success:true,data:{...sb,reviews}});}));
technicalOfficeRouter.post('/submittals',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=submittalSchema.parse(req.body);if(b.reviewer_id===req.user!.id)throw new AppError(422,'Submitter cannot be assigned as own reviewer');const [r]=await query<any>(`insert into submittals(project_id,submittal_no,type,description,submitted_by,reviewer_id,due_date,document_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.project_id,b.submittal_no,b.type,b.description,req.user!.id,b.reviewer_id??null,b.due_date??null,b.document_id??null]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.patch('/submittals/:id/review',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({status:z.enum(['submitted','under_review','approved','approved_as_noted','rejected','resubmit_required']),comment:z.string().trim().max(4000).optional()}).refine(v=>!['rejected','resubmit_required','approved_as_noted'].includes(v.status)||(v.comment??'').length>=5,{message:'Review comments required (at least 5 characters)',path:['comment']}).parse(req.body);const current=(await query<any>(`select * from submittals where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Submittal not found');const allowed:Record<string,string[]>={submitted:['under_review'],under_review:['approved','approved_as_noted','rejected','resubmit_required'],approved:[],approved_as_noted:[],rejected:['submitted'],resubmit_required:['submitted']};if(!(allowed[current.status]||[]).includes(b.status))throw new AppError(409,`Invalid submittal transition ${current.status} -> ${b.status}`);if(b.status==='submitted'){if(Number(current.submitted_by)!==req.user!.id)throw new AppError(403,'Only original submitter can resubmit');const [r]=await query<any>(`update submittals set status='submitted',reviewer_id=null,actual_response_date=null,updated_at=now() where id=$1 returning *`,[id]);return res.json({success:true,data:r});}if(Number(current.submitted_by)===req.user!.id)throw new AppError(403,'Segregation of duties: submitter cannot review own submittal');if(current.reviewer_id&&Number(current.reviewer_id)!==req.user!.id)throw new AppError(403,'Submittal is assigned to another reviewer');const [r]=await query<any>(`update submittals set status=$2::varchar,review_comment=coalesce($4::text,review_comment),reviewer_id=coalesce(reviewer_id,$3::bigint),actual_response_date=case when $2::varchar='under_review' then actual_response_date else current_date end,updated_at=now() where id=$1 returning *`,[id,b.status,req.user!.id,b.comment??null]);res.json({success:true,data:r});}));

technicalOfficeRouter.get('/rfis',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query<any>(`select *,(status='open' and response_due is not null and response_due<current_date) as overdue from rfis where ($1::bigint=0 or project_id=$1) order by raised_date desc,id desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/rfis',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=rfiSchema.parse(req.body);if(b.assigned_to===req.user!.id)throw new AppError(422,'RFI raiser cannot assign the response to self');const [r]=await query<any>(`insert into rfis(project_id,rfi_no,subject,question,raised_by,assigned_to,cost_impact_flag,time_impact_flag,response_due) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[b.project_id,b.rfi_no,b.subject,b.question,req.user!.id,b.assigned_to??null,b.cost_impact_flag,b.time_impact_flag,b.response_due??null]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.patch('/rfis/:id/respond',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({response:z.string().min(1),close:z.boolean().default(false)}).parse(req.body);const current=(await query<any>(`select * from rfis where id=$1`,[id]))[0];if(!current)throw new AppError(404,'RFI not found');if(b.close)throw new AppError(409,'Answer the RFI first, then close it using the close action');if(current.status!=='open')throw new AppError(409,'Only open RFI can be answered');if(Number(current.raised_by)===req.user!.id)throw new AppError(403,'Segregation of duties: RFI raiser cannot answer own RFI');if(current.assigned_to&&Number(current.assigned_to)!==req.user!.id)throw new AppError(403,'RFI is assigned to another user');const [r]=await query<any>(`update rfis set response=$2,response_date=current_date,responded_by=$3,status='answered',updated_at=now() where id=$1 returning *`,[id,b.response,req.user!.id]);res.json({success:true,data:r});}));
technicalOfficeRouter.post('/rfis/:id/close',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const current=(await query<any>(`select * from rfis where id=$1`,[id]))[0];if(!current)throw new AppError(404,'RFI not found');if(current.status!=='answered')throw new AppError(409,'Only answered RFI can be closed');const cb=z.object({no_impact_reason:z.string().trim().max(2000).optional()}).parse(req.body??{});const [r]=await query<any>(`update rfis set status='closed',closed_by=$2,no_impact_reason=coalesce($3::text,no_impact_reason),updated_at=now() where id=$1 returning *`,[id,req.user!.id,cb.no_impact_reason??null]);res.json({success:true,data:r});}));

technicalOfficeRouter.get('/method-statements',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query<any>(`select * from method_statements where ($1::bigint=0 or project_id=$1) order by created_at desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/method-statements',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=methodStatementSchema.parse(req.body);const [r]=await query<any>(`insert into method_statements(project_id,activity_name,document_id,status,created_by) values($1,$2,$3,'draft',$4) returning *`,[b.project_id,b.activity_name,b.document_id??null,req.user!.id]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.post('/method-statements/:id/submit',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const current=(await query<any>(`select * from method_statements where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Method statement not found');if(!['draft','rejected'].includes(current.status))throw new AppError(409,'Only draft/rejected method statement can be submitted');if(current.created_by&&Number(current.created_by)!==req.user!.id)throw new AppError(403,'Only maker can submit this method statement');const [r]=await query<any>(`update method_statements set status='submitted',submitted_by=$2,submitted_at=now(),approved_by=null,approval_date=null,updated_at=now() where id=$1 returning *`,[id,req.user!.id]);res.json({success:true,data:r});}));
technicalOfficeRouter.post('/method-statements/:id/review',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({action:z.enum(['approved','rejected']),comment:z.string().trim().max(4000).optional()}).refine(v=>v.action==='approved'||(v.comment??'').length>=5,{message:'Rejection comments required (at least 5 characters)',path:['comment']}).parse(req.body);const current=(await query<any>(`select * from method_statements where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Method statement not found');if(current.status!=='submitted')throw new AppError(409,'Method statement is not submitted');if(Number(current.created_by)===req.user!.id||Number(current.submitted_by)===req.user!.id)throw new AppError(403,'Segregation of duties: maker/submitter cannot review own method statement');const [r]=await query<any>(`update method_statements set status=$2,approved_by=$3,approval_date=current_date,review_comment=$4,updated_at=now() where id=$1 returning *`,[id,b.action,req.user!.id,b.comment??null]);res.json({success:true,data:r});}));

// Stage 16 (GC-04, migration 067): design links and revision impacts. Links tie a drawing number to the objects that
// rely on it; a new current revision opens an impact listing them; people disposition each object and close the impact
// with a contract event or a stated no-entitlement reason. The platform never decides entitlement.
const linkTypes = z.enum(['boq_item', 'activity', 'po_line', 'inspection']);
technicalOfficeRouter.post('/design-links', authorize('technical_office', 'manage'), asyncHandler(async (req, res) => {
  const b = z.object({ drawing_id: z.number().int().positive(), object_type: linkTypes, object_id: z.number().int().positive() }).parse(req.body);
  const [d] = await query<any>(`select id, project_id, drawing_no from drawings where id = $1 and org_id = $2`, [b.drawing_id, req.user!.org_id]);
  if (!d) throw new AppError(404, 'Drawing not found');
  const [l] = await query(`insert into design_links(org_id, project_id, drawing_no, object_type, object_id, based_on_drawing_id, created_by) values ($1,$2,$3,$4,$5,$6,$7) returning *`,
    [req.user!.org_id, d.project_id, d.drawing_no, b.object_type, b.object_id, d.id, req.user!.id]);
  res.status(201).json({ success: true, data: l });
}));
// Where-used: every link of a project (or of one object) with its label and whether it rests on a superseded revision.
technicalOfficeRouter.get('/design-links', asyncHandler(async (req, res) => {
  const q = z.object({ project_id: z.coerce.number().int().positive(), object_type: linkTypes.optional(), object_id: z.coerce.number().int().positive().optional() }).parse(req.query);
  res.json({ success: true, data: await query(`select l.*, d.revision as based_on_revision, (d.status = 'superseded') as stale, design_object_label(l.object_type, l.object_id, l.project_id) as object_label
     from design_links l join drawings d on d.id = l.based_on_drawing_id
     where l.org_id = $1 and l.project_id = $2 and ($3::varchar is null or l.object_type = $3::varchar) and ($4::bigint is null or l.object_id = $4::bigint)
     order by l.drawing_no, l.object_type, l.object_id`, [req.user!.org_id, q.project_id, q.object_type ?? null, q.object_id ?? null]) });
}));
technicalOfficeRouter.get('/design-impacts', asyncHandler(async (req, res) => {
  const q = z.object({ project_id: z.coerce.number().int().positive(), status: z.enum(['open', 'closed']).optional() }).parse(req.query);
  res.json({ success: true, data: await query(`select i.*, nd.revision as new_revision, sd.revision as superseded_revision,
       (select count(*)::int from design_impact_items x where x.impact_id = i.id) as items,
       (select count(*)::int from design_impact_items x where x.impact_id = i.id and x.disposition = 'pending') as pending_items
     from design_revision_impacts i join drawings nd on nd.id = i.new_drawing_id join drawings sd on sd.id = i.superseded_drawing_id
     where i.org_id = $1 and i.project_id = $2 and ($3::varchar is null or i.status = $3::varchar) order by i.id desc`, [req.user!.org_id, q.project_id, q.status ?? null]) });
}));
technicalOfficeRouter.get('/design-impacts/:id', asyncHandler(async (req, res) => {
  const [i] = await query<any>(`select * from design_revision_impacts where id = $1 and org_id = $2`, [parseId(req.params.id), req.user!.org_id]);
  if (!i) throw new AppError(404, 'Design impact not found');
  res.json({ success: true, data: { ...i, items: await query(`select * from design_impact_items where impact_id = $1 order by object_type, object_id`, [i.id]) } });
}));
technicalOfficeRouter.post('/design-impact-items/:id/disposition', authorize('technical_office', 'manage'), asyncHandler(async (req, res) => {
  const b = z.object({ disposition: z.enum(['no_change', 'change_required']), reason: z.string().trim().min(5).max(4000) }).parse(req.body);
  const [cur] = await query<any>(`select id from design_impact_items where id = $1 and org_id = $2`, [parseId(req.params.id), req.user!.org_id]);
  if (!cur) throw new AppError(404, 'Impact item not found');
  const [x] = await query(`update design_impact_items set disposition = $2::varchar, reason = $3, assessed_by = $4, assessed_at = now() where id = $1 returning *`, [cur.id, b.disposition, b.reason, req.user!.id]);
  res.json({ success: true, data: x });
}));
technicalOfficeRouter.post('/design-impacts/:id/close', authorize('technical_office', 'manage'), asyncHandler(async (req, res) => {
  const b = z.object({ contract_event_id: z.number().int().positive().optional(), no_entitlement_reason: z.string().trim().max(4000).optional() }).parse(req.body);
  const [cur] = await query<any>(`select id, status from design_revision_impacts where id = $1 and org_id = $2`, [parseId(req.params.id), req.user!.org_id]);
  if (!cur) throw new AppError(404, 'Design impact not found');
  if (cur.status === 'closed') throw new AppError(409, 'Design impact is already closed');
  const [i] = await query(`update design_revision_impacts set status = 'closed', contract_event_id = $2, no_entitlement_reason = $3, closed_by = $4, closed_at = now() where id = $1 returning *`,
    [cur.id, b.contract_event_id ?? null, b.no_entitlement_reason ?? null, req.user!.id]);
  res.json({ success: true, data: i });
}));
