import { Router } from 'express';
import { z } from 'zod';
import { query } from '../../db/pool.js';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { authorize } from '../../middleware/authorize.js';
import { AppError } from '../../middleware/errors.js';

export const technicalOfficeRouter = Router();
technicalOfficeRouter.use(authorize('technical_office', 'view'));
const parseId=(v:string)=>{const n=Number(v);if(!Number.isInteger(n)||n<=0)throw new AppError(400,'Invalid id');return n;};

const drawingSchema = z.object({project_id:z.number().int().positive(),drawing_no:z.string().min(1).max(50),title:z.string().min(1).max(255),discipline:z.string().max(50).optional(),revision:z.string().max(10).default('A'),document_id:z.number().int().positive().optional()});
const submittalSchema = z.object({project_id:z.number().int().positive(),submittal_no:z.string().min(1).max(30),type:z.enum(['material','shop_drawing','method_statement','sample','other']),description:z.string().min(1),reviewer_id:z.number().int().positive().optional(),due_date:z.string().optional(),document_id:z.number().int().positive().optional()});
const rfiSchema = z.object({project_id:z.number().int().positive(),rfi_no:z.string().min(1).max(30),subject:z.string().min(1).max(255),question:z.string().min(1),assigned_to:z.number().int().positive().optional(),cost_impact_flag:z.boolean().default(false),time_impact_flag:z.boolean().default(false)});
const methodStatementSchema = z.object({project_id:z.number().int().positive(),activity_name:z.string().min(1).max(255),document_id:z.number().int().positive().optional()});

technicalOfficeRouter.get('/drawings',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query(`select * from drawings where ($1::bigint=0 or project_id=$1) order by issued_date desc,id desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/drawings',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=drawingSchema.parse(req.body);const [r]=await query(`insert into drawings(project_id,drawing_no,title,discipline,revision,status,document_id,issued_by) values($1,$2,$3,$4,$5,'for_review',$6,$7) returning *`,[b.project_id,b.drawing_no,b.title,b.discipline??null,b.revision,b.document_id??null,req.user!.id]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.patch('/drawings/:id/status',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({status:z.enum(['for_review','approved','approved_with_comments','rejected','superseded'])}).parse(req.body);const current=(await query(`select * from drawings where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Drawing not found');const allowed:Record<string,string[]>={for_review:['approved','approved_with_comments','rejected'],approved:['superseded'],approved_with_comments:['superseded'],rejected:['for_review'],superseded:[]};if(!(allowed[current.status]||[]).includes(b.status))throw new AppError(409,`Invalid drawing transition ${current.status} -> ${b.status}`);if(['approved','approved_with_comments','rejected'].includes(b.status)&&Number(current.issued_by)===req.user!.id)throw new AppError(403,'Segregation of duties: drawing issuer cannot review own drawing');const [r]=await query(`update drawings set status=$2,reviewed_by=case when $2 in ('approved','approved_with_comments','rejected') then $3 else reviewed_by end,reviewed_at=case when $2 in ('approved','approved_with_comments','rejected') then now() else reviewed_at end,updated_at=now() where id=$1 returning *`,[id,b.status,req.user!.id]);res.json({success:true,data:r});}));

technicalOfficeRouter.get('/submittals',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query(`select * from submittals where ($1::bigint=0 or project_id=$1) order by submitted_date desc,id desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/submittals',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=submittalSchema.parse(req.body);if(b.reviewer_id===req.user!.id)throw new AppError(422,'Submitter cannot be assigned as own reviewer');const [r]=await query(`insert into submittals(project_id,submittal_no,type,description,submitted_by,reviewer_id,due_date,document_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.project_id,b.submittal_no,b.type,b.description,req.user!.id,b.reviewer_id??null,b.due_date??null,b.document_id??null]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.patch('/submittals/:id/review',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({status:z.enum(['submitted','under_review','approved','approved_as_noted','rejected','resubmit_required'])}).parse(req.body);const current=(await query(`select * from submittals where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Submittal not found');const allowed:Record<string,string[]>={submitted:['under_review'],under_review:['approved','approved_as_noted','rejected','resubmit_required'],approved:[],approved_as_noted:[],rejected:['submitted'],resubmit_required:['submitted']};if(!(allowed[current.status]||[]).includes(b.status))throw new AppError(409,`Invalid submittal transition ${current.status} -> ${b.status}`);if(b.status==='submitted'){if(Number(current.submitted_by)!==req.user!.id)throw new AppError(403,'Only original submitter can resubmit');const [r]=await query(`update submittals set status='submitted',reviewer_id=null,actual_response_date=null,updated_at=now() where id=$1 returning *`,[id]);return res.json({success:true,data:r});}if(Number(current.submitted_by)===req.user!.id)throw new AppError(403,'Segregation of duties: submitter cannot review own submittal');if(current.reviewer_id&&Number(current.reviewer_id)!==req.user!.id)throw new AppError(403,'Submittal is assigned to another reviewer');const [r]=await query(`update submittals set status=$2,reviewer_id=coalesce(reviewer_id,$3),actual_response_date=case when $2='under_review' then actual_response_date else current_date end,updated_at=now() where id=$1 returning *`,[id,b.status,req.user!.id]);res.json({success:true,data:r});}));

technicalOfficeRouter.get('/rfis',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query(`select * from rfis where ($1::bigint=0 or project_id=$1) order by raised_date desc,id desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/rfis',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=rfiSchema.parse(req.body);if(b.assigned_to===req.user!.id)throw new AppError(422,'RFI raiser cannot assign the response to self');const [r]=await query(`insert into rfis(project_id,rfi_no,subject,question,raised_by,assigned_to,cost_impact_flag,time_impact_flag) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.project_id,b.rfi_no,b.subject,b.question,req.user!.id,b.assigned_to??null,b.cost_impact_flag,b.time_impact_flag]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.patch('/rfis/:id/respond',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({response:z.string().min(1),close:z.boolean().default(false)}).parse(req.body);const current=(await query(`select * from rfis where id=$1`,[id]))[0];if(!current)throw new AppError(404,'RFI not found');if(b.close)throw new AppError(409,'Answer the RFI first, then close it using the close action');if(current.status!=='open')throw new AppError(409,'Only open RFI can be answered');if(Number(current.raised_by)===req.user!.id)throw new AppError(403,'Segregation of duties: RFI raiser cannot answer own RFI');if(current.assigned_to&&Number(current.assigned_to)!==req.user!.id)throw new AppError(403,'RFI is assigned to another user');const [r]=await query(`update rfis set response=$2,response_date=current_date,responded_by=$3,status='answered',updated_at=now() where id=$1 returning *`,[id,b.response,req.user!.id]);res.json({success:true,data:r});}));
technicalOfficeRouter.post('/rfis/:id/close',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const current=(await query(`select * from rfis where id=$1`,[id]))[0];if(!current)throw new AppError(404,'RFI not found');if(current.status!=='answered')throw new AppError(409,'Only answered RFI can be closed');const [r]=await query(`update rfis set status='closed',updated_at=now() where id=$1 returning *`,[id]);res.json({success:true,data:r});}));

technicalOfficeRouter.get('/method-statements',asyncHandler(async(req,res)=>{const projectId=Number(req.query.project_id||0);res.json({success:true,data:await query(`select * from method_statements where ($1::bigint=0 or project_id=$1) order by created_at desc limit 200`,[projectId])});}));
technicalOfficeRouter.post('/method-statements',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const b=methodStatementSchema.parse(req.body);const [r]=await query(`insert into method_statements(project_id,activity_name,document_id,status,created_by) values($1,$2,$3,'draft',$4) returning *`,[b.project_id,b.activity_name,b.document_id??null,req.user!.id]);res.status(201).json({success:true,data:r});}));
technicalOfficeRouter.post('/method-statements/:id/submit',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const current=(await query(`select * from method_statements where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Method statement not found');if(!['draft','rejected'].includes(current.status))throw new AppError(409,'Only draft/rejected method statement can be submitted');if(current.created_by&&Number(current.created_by)!==req.user!.id)throw new AppError(403,'Only maker can submit this method statement');const [r]=await query(`update method_statements set status='submitted',submitted_by=$2,submitted_at=now(),approved_by=null,approval_date=null,updated_at=now() where id=$1 returning *`,[id,req.user!.id]);res.json({success:true,data:r});}));
technicalOfficeRouter.post('/method-statements/:id/review',authorize('technical_office','manage'),asyncHandler(async(req,res)=>{const id=parseId(req.params.id);const b=z.object({action:z.enum(['approved','rejected'])}).parse(req.body);const current=(await query(`select * from method_statements where id=$1`,[id]))[0];if(!current)throw new AppError(404,'Method statement not found');if(current.status!=='submitted')throw new AppError(409,'Method statement is not submitted');if(Number(current.created_by)===req.user!.id||Number(current.submitted_by)===req.user!.id)throw new AppError(403,'Segregation of duties: maker/submitter cannot review own method statement');const [r]=await query(`update method_statements set status=$2,approved_by=$3,approval_date=current_date,updated_at=now() where id=$1 returning *`,[id,b.action,req.user!.id]);res.json({success:true,data:r});}));
