# Manual (expert) mapping of D01-D20 entities to the actual v0.2 schema (135 tables).
# Status: R = table exists and was exercised by the R0 runtime chain; S = substantive schema, not runtime-exercised;
# T = thin: exists but materially shallower than the D-spec (missing core structure); A = absent.
M = {
'D01': [('Tenant','organizations','R','organizations has RLS (CC-009); no tenant lifecycle/plan binding beyond tenant_subscriptions'),
 ('LegalEntity','organizations','T','single org row = tenant = legal entity; parent_org_id only; no legal-entity separation within a tenant'),
 ('Branch/BusinessUnit','departments','T','departments only; no BU/branch with P&L or cost-centre semantics'),
 ('Project','projects','R','runtime chain'),
 ('ProjectParticipant (JV)','','A','no JV participant model'),
 ('User','users','R','runtime chain'),
 ('Role / Permission','roles,permissions','R','runtime chain; module/action/scope only, scope not enforced beyond role'),
 ('RoleAssignment','users.role_id','T','one role per user; no project-scoped or time-bound assignments'),
 ('ApprovalPolicy / DOARule','delegation_of_authority,approval_workflow_steps','R','runtime chain; no create API; flat amount bands; not versioned/effective-dated as policy'),
 ('Party (الأساس لكل الأطراف)','clients,vendors_subcontractors','T','separate client/vendor tables; no unified Party'),
 ('Item / Service / UoM / Currency / ExchangeRate / Calendar / Country / Tax code','currencies,exchange_rates,inventory_items','T','currency/FX present; no UoM master, calendars, countries, tax codes'),
 ('NumberSequence','','A','numbers are free-text inputs'),
 ('ConfigItem','system_settings','T','key/value only; no versioned configuration layers'),
 ('AuditEvent','audit_log','S','trigger-based audit on tables (migration 017); not runtime-verified for completeness')],
'D02': [('Opportunity','opportunities,leads','R','runtime chain'),
 ('BidDecision','','A','no bid/no-bid record'),
 ('TenderDocument','tender_documents,documents','S','link table only'),
 ('TenderRequirement','','A',''),('TenderTeamAssignment','tenders.assigned_estimator_id','T','single estimator field'),
 ('Estimate (نسخ)','boq_master','T','no estimate header/versions; BOQ rows carry rates directly'),
 ('EstimateLine','boq_master','T','flat line with 4 rate columns'),
 ('BidAdjudication/Comparison','','A',''),('TenderRisk','','A',''),('BidPackage','','A',''),
 ('BidOutcome','tenders.status/awarded_value/loss_reason','S','fields on tender'),('CompetitorProfile','','A','')],
'D03': [('BOQ (رأس)','','A','no BOQ header/version/type; boq_master is a flat item table keyed by tender/project'),
 ('BOQSection','boq_master.section','T','free-text section column; no hierarchy'),
 ('BOQItem','boq_master,project_boq','T','boq_master runtime-exercised; project_boq has no creation path (F-01); no stable item id across versions'),
 ('TakeoffSheet / TakeoffLine','quantity_sheets','T','quantity_sheets is site measurement (date/location/qty), not dimensional takeoff'),
 ('RateAnalysis','boq_rate_buildup','T','runtime-exercised; no analysis header/version/output unit/overhead-profit-risk on analysis'),
 ('RateComponent','boq_rate_buildup','T','resource_type/qty_per_unit/unit_cost; no waste%, productivity ref'),
 ('Resource (مكتبة)','resource_library','T','single current rate; no specs/category'),
 ('ResourcePrice','resource_library.current_market_rate','T','no price history/source/validity/confidence'),
 ('Productivity/Norm','','A',''),('Assembly','','A',''),
 ('CostCode / CBS','cost_codes','S','hierarchical cost codes; runtime-used as FK'),
 ('UoM / Conversion','','A','unit_of_measure is free text everywhere'),('BOQTemplate','','A',''),('BOQChange','','A','')],
'D04': [('Contract','contracts','R','runtime chain'),('ContractDocument','documents','T','generic documents'),
 ('ContractClause','contract_clauses','S',''),('Obligation','','A',''),('Notice','contract_claims.notice_date','T','date field only; no notice register/time-bar engine'),
 ('Variation (VO)','variations','S','state machine fixed by CC-006; not runtime-exercised'),('VariationItem','variation_boq_lines','S','references project_boq (unpopulatable, F-01)'),
 ('ExtensionOfTime','contract_claims.claimed_days','T','claim fields only'),('Claim','contract_claims','S',''),('ClaimEvidence','','A',''),
 ('Guarantee','contracts.performance_bond_percent','T','percentage field only; no instrument record'),
 ('LDRecord','contracts.liquidated_damages_rate','T','rate field only'),('ContractValueLedger','projects.current_contract_value','T','single field; no ledger'),('Dispute','','A','')],
'D05': [('Schedule','schedule_baselines','T',''),('WBS','','A','cost_codes only; no WBS'),
 ('Activity','schedule_activities','S','single predecessor column plus relationships table; no calendars/constraints/float'),
 ('Relationship','schedule_relationships','S','type + lag'),('Calendar','','A',''),('ActivityResourceAssignment','','A',''),
 ('ActivityBOQLink','progress_updates.boq_item_id','T',''),('ProgressRecord','progress_updates','S',''),('Baseline','schedule_baselines','T','no activity snapshot per baseline'),
 ('Constraint/Readiness (Make-Ready)','','A',''),('EVMSnapshot','evm_snapshots','S','fields present; no computation engine verified'),
 ('CashflowForecast','cash_flow_forecast','S',''),('DelayEvent','','A',''),('Risk-on-schedule','','A','')],
'D06': [('PurchaseRequisition / Line','material_requisitions,mr_lines','R','runtime chain'),('RFQ / RFQLine / RFQInvite','rfqs,rfq_vendors','R','no RFQ lines'),
 ('Quotation','vendor_quotations','R','header total only; no quotation lines'),('QuoteComparison','comparative_statements','R','header only; no line comparison'),
 ('Vendor (مرجع D01) + VendorProfile','vendors_subcontractors','T','no create API (F-02)'),('VendorEvaluation','vendors_subcontractors.rating_score','T',''),
 ('PurchaseOrder / POLine','purchase_orders,po_lines','R','runtime chain'),('POAmendment','','A',''),('FrameworkAgreement','','A',''),
 ('GoodsReceipt (GRN) / Line','goods_receipt_notes,grn_lines','R','runtime chain'),('SupplierInvoice / Line','vendor_invoices','R','no invoice lines'),
 ('MatchResult','invoice_match_results','R','runtime chain'),('Commitment','cost_transactions(committed)','R','created on PO approval'),
 ('Shipment / CustomsFile','','A',''),('ExpediteLog','','A','')],
'D07': [('SubcontractorPrequal','vendors_subcontractors.prequalification_status','T',''),('SubPackage / Line','subcontracts.package_name','T',''),
 ('SubTender / SubBid / Comparison','','A',''),('SubContract','subcontracts','S',''),('SubContractItem','','A','no subcontract BOQ'),('WorkOrder','','A',''),
 ('MeasurementSheet / Line','quantity_sheets','T',''),('PaymentCertificate (Sub IPC)','subcontract_certificates,subcontract_certificate_lines','S','posting path exists; not runtime-exercised'),
 ('IPCDeduction','subcontract_certificates.penalties_deductions','T','single field'),('BackCharge','','A',''),('SubVO','','A',''),
 ('OwnerIPC','ipcs,ipc_boq_lines','R','header runtime-exercised; ipc_boq_lines need project_boq (F-01)'),('Guarantee (ref)','','A',''),('FinalAccount','','A',''),('MarginView','','A','')],
'D08': [('DailyReport','site_diary','S',''),('DR_Labor / DR_Equipment','diary_manpower,diary_equipment','S',''),('DR_Work / ExecutedQuantity','quantity_sheets,progress_updates','T',''),
 ('DR_Material / DR_Delay / DR_Incident','site_diary.delays_notes,incidents','T','free text'),('Location/Zone','','A','location is free text'),
 ('RFI','rfis','S',''),('Submittal','submittals','S',''),('SubmittalRevision','','A',''),('DrawingRegister / DrawingRevision','drawings','T','revision column only; no revision history table'),
 ('ShopDrawing','','A',''),('InspectionRequest','inspection_checklists','T',''),('SiteInstruction','site_instructions','S',''),
 ('Meeting / Minute / ActionItem','','A',''),('Photo','documents','T',''),('SnagItem / HandoverPack','punch_lists','T',''),('SyncBatch / Conflict','','A','no offline sync')],
'D09': [('QualityPlan','','A',''),('ITPTemplate / ITP','','A',''),('ITPStep','','A',''),('InspectionRequest (IR)','inspection_checklists','T',''),
 ('InspectionChecklist / Result','inspection_checklists','T','header only; no checklist items/results'),('HoldPointRelease','','A',''),('MaterialSample','','A',''),('TestResult','','A',''),
 ('Lab / LabAccreditation','','A',''),('NCR','ncrs','S',''),('CAR / CorrectiveAction','ncrs.corrective_action','T','text field'),('SnagItem','punch_lists','S',''),
 ('CalibrationRecord','','A',''),('SupplierQualityRecord','','A',''),('AuditPlan / Audit','','A',''),('HandoverDossier','','A','')],
'D10': [('HSEPlan','','A',''),('RiskAssessment / RiskItem','','A',''),('JSA / MethodStatement','method_statements','T','header only'),('PermitToWork','permits_to_work','S','lifecycle columns present'),
 ('PermitCheck / Closure','permits_to_work.closed_by','T',''),('IncidentReport','incidents','S',''),('Injury / MedicalCase','incidents.injured_party','T',''),
 ('Investigation','incidents.investigation_status','T',''),('CorrectiveAction','incidents.corrective_actions','T','text'),('Inspection / Audit','','A',''),
 ('CompetencyRequirement','','A',''),('TrainingRecord','','A',''),('ToolboxTalk','toolbox_talks','S',''),('PPEIssue','','A',''),('EmergencyPlan / Drill','','A',''),
 ('EnvMonitoring','','A',''),('WasteRecord','','A',''),('ContractorHSEProfile','','A',''),('StopWorkEvent','','A',''),('ExposureHours','','A','')],
'D11': [('Equipment (Asset)','assets_equipment','S',''),('EquipmentCategory','assets_equipment.category','T',''),('EquipmentDocument','','A',''),
 ('Allocation','assets_equipment.current_project_id','T',''),('TransferRecord','','A',''),('UsageLog','equipment_usage','S','posts cost'),('OperatorAssignment','equipment_usage.operator_id','T',''),
 ('FuelTransaction','','A',''),('MaintenancePlan','maintenance_log.next_due_date','T',''),('WorkOrder','maintenance_log','T',''),('Breakdown / Downtime','','A',''),
 ('InternalRate','equipment_usage.hourly_rate','T','per-usage rate; no rate card'),('ChargeRun / Charge','','A',''),('RentalContract','','A',''),('RentalInvoiceMatch','','A',''),
 ('TelematicsDevice / Event','','A',''),('AssetFinancials','','A','')],
'D12': [('Employee','employees','S',''),('EmployeeContract','employees.employment_type/basic_salary','T',''),('OrgPosition','employees.job_title','T','no position catalog'),
 ('Requisition / Candidate / Offer','recruitment','T','requisition only'),('ProjectAssignment','employees.primary_project_id','T',''),('Shift / AttendanceRule','','A',''),
 ('AttendanceEvent','','A',''),('DailyAttendance','attendance','S',''),('Timesheet / TimesheetLine','timesheets','S',''),('LeaveType / LeaveBalance / LeaveRequest','leave_requests','T','requests only'),
 ('PayElement','payroll_lines.basic/overtime/allowances','T','fixed columns'),('PayrollRun / PayslipLine','payroll_runs,payroll_lines','S','posts cost/GL; not runtime-exercised'),
 ('StatutoryProfile','','A','no statutory/social-insurance/tax rules'),('EndOfService','','A',''),('IdentityDocument','employees.national_id','T',''),('Camp / Room / Bed / Occupancy','','A',''),
 ('DailyWorker / SubcontractWorker','diary_manpower','T','headcount only'),('Appraisal / TrainingRecord','','A','')],
'D13': [('LegalEntity / FiscalCalendar / Period','fiscal_periods','R','runtime chain'),('ChartOfAccount / Account','chart_of_accounts','R','runtime chain'),
 ('CostCode ↔ Account Mapping','gl_posting_rules','T','posting rule by source module, not by cost code'),('JournalEntry / JournalLine','general_ledger,manual_journal_entries,manual_journal_entry_lines','R','GL runtime-exercised; manual journals not'),
 ('Dimension','general_ledger.project_id','T','project only'),('Currency / FXRate','currencies,exchange_rates','S',''),('Vendor/Customer (Party financial)','clients,vendors_subcontractors','T',''),
 ('APInvoice / ARInvoice','accounts_payable,accounts_receivable,vendor_invoices','R','runtime chain'),('Payment / Receipt / Allocation','payments','R','runtime chain; no allocation table'),
 ('BankAccount / BankStatementLine / Reconciliation','bank_accounts,bank_reconciliation','T','no statement lines'),('Commitment','cost_transactions','R',''),
 ('Budget / BudgetRevision','budgets','T','no revisions'),('RetentionLedger','retention_ledger','S','not populated by IPC path in runtime chain'),('GuaranteeRecord','','A',''),
 ('WIPSnapshot','','A',''),('RevenueRecognitionPolicy','','A','F-05 open decision'),('FixedAssetRegister','assets_equipment','T','operational asset, not financial register'),
 ('IntercompanyPair','','A',''),('TaxCode / TaxLedger','vendor_invoices.tax_amount','T','amount only'),('PeriodCloseChecklist','fiscal_periods.status','T','')],
'D14': [('Item','inventory_items','R',''),('ItemUoM','','A',''),('Warehouse','warehouses','R',''),('Location/Bin','','A',''),('StockBalance','','A','derived from transactions only'),
 ('StockMovement','inventory_transactions','R',''),('GoodsReceipt','goods_receipt_notes','R',''),('IssueNote','inventory_transactions(issue)','T',''),('TransferOrder','inventory_transactions(transfer)','T','transfer endpoint exists; not runtime-exercised'),
 ('ReturnNote','','A',''),('Reservation','','A',''),('Stocktake / StocktakeLine','','A',''),('ReorderPolicy','','A',''),('ValuationPolicy','','A','unit_cost per transaction only'),
 ('ConsumptionNorm','','A',''),('ScrapSurplus','','A',''),('Barcode/QRTag','','A','')],
'D15': [('Document (هوية)','documents','S',''),('DocumentRevision','document_versions','S','sha256/storage key'),('MetadataSchema','','A',''),('NumberingRule','document_registers.numbering_scheme','T',''),
 ('StatusCodeSet','','A',''),('Transmittal / TransmittalLine','document_transmittals,transmittal_lines','S',''),('Submittal','submittals','S',''),('RFI','rfis','S',''),
 ('Correspondence','','A',''),('MeetingMinutes / ActionItem','','A',''),('DistributionMatrix','','A',''),('ReviewStamp','','A',''),('AccessGrant','documents.confidentiality','T',''),
 ('ExternalShare','client_portal_access,subcontractor_portal_access','T',''),('RetentionPolicy / LegalHold','','A',''),('ObligationLink','','A',''),('EvidencePack','ipc_supporting_docs','T','IPC only')],
'D16': [('DrawingSheet','drawings','S',''),('DrawingRevision','drawings.revision','T',''),('ModelFile / ModelVersion','','A',''),('ModelElement (Index)','','A',''),('ElementLink','','A',''),
 ('InformationRequirement','','A',''),('ModelQualityReport','','A',''),('ClashTest / ClashResult','','A',''),('DesignIssue (BCF-style)','','A',''),('DesignChange','','A',''),
 ('VEProposal','','A',''),('SpecItem / SpecLibrary','','A',''),('CalcNote (سجل مذكرات حسابية)','','A',''),('AsBuiltRecord','','A',''),('HandoverPackage / AssetDataRow','','A','')],
'D17': [('RiskRegister','','A',''),('Risk','','A',''),('RiskScale','','A',''),('MitigationAction','','A',''),('RiskQuant','','A',''),('Contingency / Reserve','','A',''),('QuantRun','','A',''),
 ('InsurancePolicy','','A',''),('PolicyRequirement','','A',''),('InsuranceClaim / Incident','','A',''),('Guarantee (Bond/LG)','','A','tenders.bond_amount only'),('GuaranteeRequest','','A',''),
 ('GuaranteeEvent','','A',''),('BankFacility','','A',''),('Surety / BondProvider','','A',''),('CounterpartyRisk','','A',''),('FXExposure','','A',''),('EarlyWarningIndicator','','A','')],
'D18': [('MetricDefinition','','A',''),('Dimension','','A',''),('DataMart / FactTable','','A','dashboards query OLTP directly'),('MetricSnapshot','evm_snapshots,company_cash_position','T',''),('Lineage','','A',''),
 ('Dashboard','','A','hard-coded pages'),('Widget','','A',''),('Report / ReportTemplate','','A',''),('Schedule (توزيع)','','A',''),('ThresholdRule / Alert','notifications','T',''),
 ('ReconciliationRun','','A',''),('ExportLog','','A','')],
'D19': [(e,'','A','') for e in ['JVArrangement','JVPartner','ShareSchedule','JVAccountingPolicy','PartnerView / PartnerLedger','CashCall','Distribution','PartnerCurrentAccount','IntercompanyTransaction','EliminationRule / EliminationEntry','GroupChartMapping','ConsolidationRun','TranslationSet','MinorityInterest','ResourceChargeRule / ResourceCharge','SharedServiceAllocation','GroupDOAPolicy','PartnerPortalAccount']] + [('ConsolidationGroup / Ownership','organizations.parent_org_id','T','parent pointer only')],
'D20': [('Tenant / Plan / Entitlement','organizations,subscription_plans,plan_entitlements,tenant_subscriptions,feature_catalog','S','no provisioning flow (F-03/F-08)'),
 ('Environment / Release','','A',''),('ProvisioningJob','customer_onboarding','T','checklist only'),('Secret / KeyRef','integration_connections.secret_ref','T',''),
 ('ApiClient / ApiKey / RateLimitPolicy','','A',''),('Connector (Catalog)','','A',''),('ConnectorInstance','integration_connections','S',''),('FieldMapping / MappingVersion','','A',''),
 ('IntegrationRun / DeadLetter','automation_executions','T',''),('WebhookSubscription','webhook_subscriptions','S','no delivery worker verified'),('AutomationFlow (External)','automation_workflows','S',''),
 ('MCPServer / MCPTool','ai_tools','T',''),('ModelRegistry','ai_models','S',''),('PromptRegistry','ai_prompts','S',''),('ToolRegistry / SkillRegistry / AgentRegistry','ai_tools,ai_agents,ai_agent_tools','S','no runtime agent execution verified'),
 ('AIRequestLog','ai_runs,ai_run_steps','S',''),('EvalSuite / EvalRun / GoldenSet','ai_evaluations','T',''),('AIBudget / Quota','ai_agents.cost_limit,usage_events','T',''),('KillSwitch','ai_agents.kill_switch','T','per-agent flag'),
 ('BrainConfig / ConfigVersion','','A','no versioned company configuration layer'),('FeatureFlag','feature_catalog','T',''),('LocalizationPack / BrandPack','','A',''),('Extension / ExtensionInstall','','A',''),
 ('SupportSession','','A',''),('BackupJob / RestoreTest','','A',''),('TenantExport / DeletionCertificate','','A','')],
}
